// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: endpoint.proto

package iroha.protocol;

public final class Endpoint {
  private Endpoint() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code iroha.protocol.TxStatus}
   */
  public enum TxStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATELESS_VALIDATION_FAILED = 0;</code>
     */
    STATELESS_VALIDATION_FAILED(0),
    /**
     * <code>STATELESS_VALIDATION_SUCCESS = 1;</code>
     */
    STATELESS_VALIDATION_SUCCESS(1),
    /**
     * <code>STATEFUL_VALIDATION_FAILED = 2;</code>
     */
    STATEFUL_VALIDATION_FAILED(2),
    /**
     * <code>STATEFUL_VALIDATION_SUCCESS = 3;</code>
     */
    STATEFUL_VALIDATION_SUCCESS(3),
    /**
     * <code>COMMITTED = 4;</code>
     */
    COMMITTED(4),
    /**
     * <code>NOT_RECEIVED = 5;</code>
     */
    NOT_RECEIVED(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATELESS_VALIDATION_FAILED = 0;</code>
     */
    public static final int STATELESS_VALIDATION_FAILED_VALUE = 0;
    /**
     * <code>STATELESS_VALIDATION_SUCCESS = 1;</code>
     */
    public static final int STATELESS_VALIDATION_SUCCESS_VALUE = 1;
    /**
     * <code>STATEFUL_VALIDATION_FAILED = 2;</code>
     */
    public static final int STATEFUL_VALIDATION_FAILED_VALUE = 2;
    /**
     * <code>STATEFUL_VALIDATION_SUCCESS = 3;</code>
     */
    public static final int STATEFUL_VALIDATION_SUCCESS_VALUE = 3;
    /**
     * <code>COMMITTED = 4;</code>
     */
    public static final int COMMITTED_VALUE = 4;
    /**
     * <code>NOT_RECEIVED = 5;</code>
     */
    public static final int NOT_RECEIVED_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static TxStatus valueOf(int value) {
      return forNumber(value);
    }

    public static TxStatus forNumber(int value) {
      switch (value) {
        case 0: return STATELESS_VALIDATION_FAILED;
        case 1: return STATELESS_VALIDATION_SUCCESS;
        case 2: return STATEFUL_VALIDATION_FAILED;
        case 3: return STATEFUL_VALIDATION_SUCCESS;
        case 4: return COMMITTED;
        case 5: return NOT_RECEIVED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TxStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TxStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TxStatus>() {
            public TxStatus findValueByNumber(int number) {
              return TxStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Endpoint.getDescriptor().getEnumTypes().get(0);
    }

    private static final TxStatus[] VALUES = values();

    public static TxStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TxStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:iroha.protocol.TxStatus)
  }

  public interface ToriiResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.ToriiResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    int getTxStatusValue();
    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    TxStatus getTxStatus();

    /**
     * <code>bytes tx_hash = 2;</code>
     */
    com.google.protobuf.ByteString getTxHash();
  }
  /**
   * Protobuf type {@code iroha.protocol.ToriiResponse}
   */
  public  static final class ToriiResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.ToriiResponse)
      ToriiResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToriiResponse.newBuilder() to construct.
    private ToriiResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToriiResponse() {
      txStatus_ = 0;
      txHash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToriiResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              txStatus_ = rawValue;
              break;
            }
            case 18: {

              txHash_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Endpoint.internal_static_iroha_protocol_ToriiResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Endpoint.internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ToriiResponse.class, Builder.class);
    }

    public static final int TX_STATUS_FIELD_NUMBER = 1;
    private int txStatus_;
    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    public int getTxStatusValue() {
      return txStatus_;
    }
    /**
     * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
     */
    public TxStatus getTxStatus() {
      TxStatus result = TxStatus.valueOf(txStatus_);
      return result == null ? TxStatus.UNRECOGNIZED : result;
    }

    public static final int TX_HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString txHash_;
    /**
     * <code>bytes tx_hash = 2;</code>
     */
    public com.google.protobuf.ByteString getTxHash() {
      return txHash_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (txStatus_ != TxStatus.STATELESS_VALIDATION_FAILED.getNumber()) {
        output.writeEnum(1, txStatus_);
      }
      if (!txHash_.isEmpty()) {
        output.writeBytes(2, txHash_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (txStatus_ != TxStatus.STATELESS_VALIDATION_FAILED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, txStatus_);
      }
      if (!txHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, txHash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ToriiResponse)) {
        return super.equals(obj);
      }
      ToriiResponse other = (ToriiResponse) obj;

      boolean result = true;
      result = result && txStatus_ == other.txStatus_;
      result = result && getTxHash()
          .equals(other.getTxHash());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + txStatus_;
      hash = (37 * hash) + TX_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getTxHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ToriiResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ToriiResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ToriiResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ToriiResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ToriiResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ToriiResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ToriiResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ToriiResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ToriiResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ToriiResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ToriiResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ToriiResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ToriiResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.ToriiResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.ToriiResponse)
        ToriiResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Endpoint.internal_static_iroha_protocol_ToriiResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Endpoint.internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ToriiResponse.class, Builder.class);
      }

      // Construct using iroha.protocol.Endpoint.ToriiResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        txStatus_ = 0;

        txHash_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Endpoint.internal_static_iroha_protocol_ToriiResponse_descriptor;
      }

      public ToriiResponse getDefaultInstanceForType() {
        return ToriiResponse.getDefaultInstance();
      }

      public ToriiResponse build() {
        ToriiResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ToriiResponse buildPartial() {
        ToriiResponse result = new ToriiResponse(this);
        result.txStatus_ = txStatus_;
        result.txHash_ = txHash_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ToriiResponse) {
          return mergeFrom((ToriiResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ToriiResponse other) {
        if (other == ToriiResponse.getDefaultInstance()) return this;
        if (other.txStatus_ != 0) {
          setTxStatusValue(other.getTxStatusValue());
        }
        if (other.getTxHash() != com.google.protobuf.ByteString.EMPTY) {
          setTxHash(other.getTxHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ToriiResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ToriiResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int txStatus_ = 0;
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public int getTxStatusValue() {
        return txStatus_;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public Builder setTxStatusValue(int value) {
        txStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public TxStatus getTxStatus() {
        TxStatus result = TxStatus.valueOf(txStatus_);
        return result == null ? TxStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public Builder setTxStatus(TxStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        txStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.iroha.protocol.TxStatus tx_status = 1;</code>
       */
      public Builder clearTxStatus() {
        
        txStatus_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString txHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes tx_hash = 2;</code>
       */
      public com.google.protobuf.ByteString getTxHash() {
        return txHash_;
      }
      /**
       * <code>bytes tx_hash = 2;</code>
       */
      public Builder setTxHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes tx_hash = 2;</code>
       */
      public Builder clearTxHash() {
        
        txHash_ = getDefaultInstance().getTxHash();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.ToriiResponse)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.ToriiResponse)
    private static final ToriiResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ToriiResponse();
    }

    public static ToriiResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToriiResponse>
        PARSER = new com.google.protobuf.AbstractParser<ToriiResponse>() {
      public ToriiResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToriiResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToriiResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ToriiResponse> getParserForType() {
      return PARSER;
    }

    public ToriiResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxStatusRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.TxStatusRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes tx_hash = 1;</code>
     */
    com.google.protobuf.ByteString getTxHash();
  }
  /**
   * Protobuf type {@code iroha.protocol.TxStatusRequest}
   */
  public  static final class TxStatusRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.TxStatusRequest)
      TxStatusRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxStatusRequest.newBuilder() to construct.
    private TxStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxStatusRequest() {
      txHash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxStatusRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              txHash_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Endpoint.internal_static_iroha_protocol_TxStatusRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Endpoint.internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxStatusRequest.class, Builder.class);
    }

    public static final int TX_HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString txHash_;
    /**
     * <code>bytes tx_hash = 1;</code>
     */
    public com.google.protobuf.ByteString getTxHash() {
      return txHash_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!txHash_.isEmpty()) {
        output.writeBytes(1, txHash_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!txHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, txHash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxStatusRequest)) {
        return super.equals(obj);
      }
      TxStatusRequest other = (TxStatusRequest) obj;

      boolean result = true;
      result = result && getTxHash()
          .equals(other.getTxHash());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getTxHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxStatusRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.TxStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.TxStatusRequest)
        TxStatusRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Endpoint.internal_static_iroha_protocol_TxStatusRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Endpoint.internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxStatusRequest.class, Builder.class);
      }

      // Construct using iroha.protocol.Endpoint.TxStatusRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        txHash_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Endpoint.internal_static_iroha_protocol_TxStatusRequest_descriptor;
      }

      public TxStatusRequest getDefaultInstanceForType() {
        return TxStatusRequest.getDefaultInstance();
      }

      public TxStatusRequest build() {
        TxStatusRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TxStatusRequest buildPartial() {
        TxStatusRequest result = new TxStatusRequest(this);
        result.txHash_ = txHash_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxStatusRequest) {
          return mergeFrom((TxStatusRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxStatusRequest other) {
        if (other == TxStatusRequest.getDefaultInstance()) return this;
        if (other.getTxHash() != com.google.protobuf.ByteString.EMPTY) {
          setTxHash(other.getTxHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxStatusRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxStatusRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString txHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes tx_hash = 1;</code>
       */
      public com.google.protobuf.ByteString getTxHash() {
        return txHash_;
      }
      /**
       * <code>bytes tx_hash = 1;</code>
       */
      public Builder setTxHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes tx_hash = 1;</code>
       */
      public Builder clearTxHash() {
        
        txHash_ = getDefaultInstance().getTxHash();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.TxStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.TxStatusRequest)
    private static final TxStatusRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxStatusRequest();
    }

    public static TxStatusRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<TxStatusRequest>() {
      public TxStatusRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxStatusRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxStatusRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TxStatusRequest> getParserForType() {
      return PARSER;
    }

    public TxStatusRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_ToriiResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_TxStatusRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016endpoint.proto\022\016iroha.protocol\032\rquerie" +
      "s.proto\032\033google/protobuf/empty.proto\032\013bl" +
      "ock.proto\032\017responses.proto\"M\n\rToriiRespo" +
      "nse\022+\n\ttx_status\030\001 \001(\0162\030.iroha.protocol." +
      "TxStatus\022\017\n\007tx_hash\030\002 \001(\014\"\"\n\017TxStatusReq" +
      "uest\022\017\n\007tx_hash\030\001 \001(\014*\257\001\n\010TxStatus\022\037\n\033ST" +
      "ATELESS_VALIDATION_FAILED\020\000\022 \n\034STATELESS" +
      "_VALIDATION_SUCCESS\020\001\022\036\n\032STATEFUL_VALIDA" +
      "TION_FAILED\020\002\022\037\n\033STATEFUL_VALIDATION_SUC" +
      "CESS\020\003\022\r\n\tCOMMITTED\020\004\022\020\n\014NOT_RECEIVED\020\0052" +
      "\352\001\n\016CommandService\022<\n\005Torii\022\033.iroha.prot" +
      "ocol.Transaction\032\026.google.protobuf.Empty" +
      "\022H\n\006Status\022\037.iroha.protocol.TxStatusRequ" +
      "est\032\035.iroha.protocol.ToriiResponse\022P\n\014St" +
      "atusStream\022\037.iroha.protocol.TxStatusRequ" +
      "est\032\035.iroha.protocol.ToriiResponse0\0012L\n\014" +
      "QueryService\022<\n\004Find\022\025.iroha.protocol.Qu" +
      "ery\032\035.iroha.protocol.QueryResponseb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Queries.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          Block.getDescriptor(),
          iroha.protocol.Responses.getDescriptor(),
        }, assigner);
    internal_static_iroha_protocol_ToriiResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iroha_protocol_ToriiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_ToriiResponse_descriptor,
        new String[] { "TxStatus", "TxHash", });
    internal_static_iroha_protocol_TxStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iroha_protocol_TxStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_TxStatusRequest_descriptor,
        new String[] { "TxHash", });
    Queries.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    Block.getDescriptor();
    iroha.protocol.Responses.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
