// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: primitive.proto

package iroha.protocol;

public final class Primitive {
  private Primitive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * Represents any possible value for permission field,
   * then the account is capable of performing such action.
   * Command and Query related permissions are included in the role,
   * which an Account can have.
   * Grantable permission is set as a relation between two accounts:
   * Account A is granting Permission to Account B,
   * so that Account B can perform actions over Account A.
   * </pre>
   *
   * Protobuf enum {@code iroha.protocol.RolePermission}
   */
  public enum RolePermission
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Command Permissions
     * </pre>
     *
     * <code>can_append_role = 0;</code>
     */
    can_append_role(0),
    /**
     * <code>can_create_role = 1;</code>
     */
    can_create_role(1),
    /**
     * <code>can_detach_role = 2;</code>
     */
    can_detach_role(2),
    /**
     * <code>can_add_asset_qty = 3;</code>
     */
    can_add_asset_qty(3),
    /**
     * <code>can_subtract_asset_qty = 4;</code>
     */
    can_subtract_asset_qty(4),
    /**
     * <code>can_add_peer = 5;</code>
     */
    can_add_peer(5),
    /**
     * <code>can_add_signatory = 6;</code>
     */
    can_add_signatory(6),
    /**
     * <code>can_remove_signatory = 7;</code>
     */
    can_remove_signatory(7),
    /**
     * <code>can_set_quorum = 8;</code>
     */
    can_set_quorum(8),
    /**
     * <code>can_create_account = 9;</code>
     */
    can_create_account(9),
    /**
     * <code>can_set_detail = 10;</code>
     */
    can_set_detail(10),
    /**
     * <code>can_create_asset = 11;</code>
     */
    can_create_asset(11),
    /**
     * <code>can_transfer = 12;</code>
     */
    can_transfer(12),
    /**
     * <code>can_receive = 13;</code>
     */
    can_receive(13),
    /**
     * <code>can_create_domain = 14;</code>
     */
    can_create_domain(14),
    /**
     * <pre>
     * Query permissions
     * </pre>
     *
     * <code>can_read_assets = 15;</code>
     */
    can_read_assets(15),
    /**
     * <code>can_get_roles = 16;</code>
     */
    can_get_roles(16),
    /**
     * <code>can_get_my_account = 17;</code>
     */
    can_get_my_account(17),
    /**
     * <code>can_get_all_accounts = 18;</code>
     */
    can_get_all_accounts(18),
    /**
     * <code>can_get_domain_accounts = 19;</code>
     */
    can_get_domain_accounts(19),
    /**
     * <code>can_get_my_signatories = 20;</code>
     */
    can_get_my_signatories(20),
    /**
     * <code>can_get_all_signatories = 21;</code>
     */
    can_get_all_signatories(21),
    /**
     * <code>can_get_domain_signatories = 22;</code>
     */
    can_get_domain_signatories(22),
    /**
     * <code>can_get_my_acc_ast = 23;</code>
     */
    can_get_my_acc_ast(23),
    /**
     * <code>can_get_all_acc_ast = 24;</code>
     */
    can_get_all_acc_ast(24),
    /**
     * <code>can_get_domain_acc_ast = 25;</code>
     */
    can_get_domain_acc_ast(25),
    /**
     * <code>can_get_my_acc_detail = 26;</code>
     */
    can_get_my_acc_detail(26),
    /**
     * <code>can_get_all_acc_detail = 27;</code>
     */
    can_get_all_acc_detail(27),
    /**
     * <code>can_get_domain_acc_detail = 28;</code>
     */
    can_get_domain_acc_detail(28),
    /**
     * <code>can_get_my_acc_txs = 29;</code>
     */
    can_get_my_acc_txs(29),
    /**
     * <code>can_get_all_acc_txs = 30;</code>
     */
    can_get_all_acc_txs(30),
    /**
     * <code>can_get_domain_acc_txs = 31;</code>
     */
    can_get_domain_acc_txs(31),
    /**
     * <code>can_get_my_acc_ast_txs = 32;</code>
     */
    can_get_my_acc_ast_txs(32),
    /**
     * <code>can_get_all_acc_ast_txs = 33;</code>
     */
    can_get_all_acc_ast_txs(33),
    /**
     * <code>can_get_domain_acc_ast_txs = 34;</code>
     */
    can_get_domain_acc_ast_txs(34),
    /**
     * <code>can_get_my_txs = 35;</code>
     */
    can_get_my_txs(35),
    /**
     * <code>can_get_all_txs = 36;</code>
     */
    can_get_all_txs(36),
    /**
     * <pre>
     * Grant permissions
     * </pre>
     *
     * <code>can_grant_can_set_quorum = 37;</code>
     */
    can_grant_can_set_quorum(37),
    /**
     * <code>can_grant_can_add_signatory = 38;</code>
     */
    can_grant_can_add_signatory(38),
    /**
     * <code>can_grant_can_remove_signatory = 39;</code>
     */
    can_grant_can_remove_signatory(39),
    /**
     * <code>can_grant_can_transfer = 40;</code>
     */
    can_grant_can_transfer(40),
    /**
     * <code>can_grant_can_set_detail = 41;</code>
     */
    can_grant_can_set_detail(41),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Command Permissions
     * </pre>
     *
     * <code>can_append_role = 0;</code>
     */
    public static final int can_append_role_VALUE = 0;
    /**
     * <code>can_create_role = 1;</code>
     */
    public static final int can_create_role_VALUE = 1;
    /**
     * <code>can_detach_role = 2;</code>
     */
    public static final int can_detach_role_VALUE = 2;
    /**
     * <code>can_add_asset_qty = 3;</code>
     */
    public static final int can_add_asset_qty_VALUE = 3;
    /**
     * <code>can_subtract_asset_qty = 4;</code>
     */
    public static final int can_subtract_asset_qty_VALUE = 4;
    /**
     * <code>can_add_peer = 5;</code>
     */
    public static final int can_add_peer_VALUE = 5;
    /**
     * <code>can_add_signatory = 6;</code>
     */
    public static final int can_add_signatory_VALUE = 6;
    /**
     * <code>can_remove_signatory = 7;</code>
     */
    public static final int can_remove_signatory_VALUE = 7;
    /**
     * <code>can_set_quorum = 8;</code>
     */
    public static final int can_set_quorum_VALUE = 8;
    /**
     * <code>can_create_account = 9;</code>
     */
    public static final int can_create_account_VALUE = 9;
    /**
     * <code>can_set_detail = 10;</code>
     */
    public static final int can_set_detail_VALUE = 10;
    /**
     * <code>can_create_asset = 11;</code>
     */
    public static final int can_create_asset_VALUE = 11;
    /**
     * <code>can_transfer = 12;</code>
     */
    public static final int can_transfer_VALUE = 12;
    /**
     * <code>can_receive = 13;</code>
     */
    public static final int can_receive_VALUE = 13;
    /**
     * <code>can_create_domain = 14;</code>
     */
    public static final int can_create_domain_VALUE = 14;
    /**
     * <pre>
     * Query permissions
     * </pre>
     *
     * <code>can_read_assets = 15;</code>
     */
    public static final int can_read_assets_VALUE = 15;
    /**
     * <code>can_get_roles = 16;</code>
     */
    public static final int can_get_roles_VALUE = 16;
    /**
     * <code>can_get_my_account = 17;</code>
     */
    public static final int can_get_my_account_VALUE = 17;
    /**
     * <code>can_get_all_accounts = 18;</code>
     */
    public static final int can_get_all_accounts_VALUE = 18;
    /**
     * <code>can_get_domain_accounts = 19;</code>
     */
    public static final int can_get_domain_accounts_VALUE = 19;
    /**
     * <code>can_get_my_signatories = 20;</code>
     */
    public static final int can_get_my_signatories_VALUE = 20;
    /**
     * <code>can_get_all_signatories = 21;</code>
     */
    public static final int can_get_all_signatories_VALUE = 21;
    /**
     * <code>can_get_domain_signatories = 22;</code>
     */
    public static final int can_get_domain_signatories_VALUE = 22;
    /**
     * <code>can_get_my_acc_ast = 23;</code>
     */
    public static final int can_get_my_acc_ast_VALUE = 23;
    /**
     * <code>can_get_all_acc_ast = 24;</code>
     */
    public static final int can_get_all_acc_ast_VALUE = 24;
    /**
     * <code>can_get_domain_acc_ast = 25;</code>
     */
    public static final int can_get_domain_acc_ast_VALUE = 25;
    /**
     * <code>can_get_my_acc_detail = 26;</code>
     */
    public static final int can_get_my_acc_detail_VALUE = 26;
    /**
     * <code>can_get_all_acc_detail = 27;</code>
     */
    public static final int can_get_all_acc_detail_VALUE = 27;
    /**
     * <code>can_get_domain_acc_detail = 28;</code>
     */
    public static final int can_get_domain_acc_detail_VALUE = 28;
    /**
     * <code>can_get_my_acc_txs = 29;</code>
     */
    public static final int can_get_my_acc_txs_VALUE = 29;
    /**
     * <code>can_get_all_acc_txs = 30;</code>
     */
    public static final int can_get_all_acc_txs_VALUE = 30;
    /**
     * <code>can_get_domain_acc_txs = 31;</code>
     */
    public static final int can_get_domain_acc_txs_VALUE = 31;
    /**
     * <code>can_get_my_acc_ast_txs = 32;</code>
     */
    public static final int can_get_my_acc_ast_txs_VALUE = 32;
    /**
     * <code>can_get_all_acc_ast_txs = 33;</code>
     */
    public static final int can_get_all_acc_ast_txs_VALUE = 33;
    /**
     * <code>can_get_domain_acc_ast_txs = 34;</code>
     */
    public static final int can_get_domain_acc_ast_txs_VALUE = 34;
    /**
     * <code>can_get_my_txs = 35;</code>
     */
    public static final int can_get_my_txs_VALUE = 35;
    /**
     * <code>can_get_all_txs = 36;</code>
     */
    public static final int can_get_all_txs_VALUE = 36;
    /**
     * <pre>
     * Grant permissions
     * </pre>
     *
     * <code>can_grant_can_set_quorum = 37;</code>
     */
    public static final int can_grant_can_set_quorum_VALUE = 37;
    /**
     * <code>can_grant_can_add_signatory = 38;</code>
     */
    public static final int can_grant_can_add_signatory_VALUE = 38;
    /**
     * <code>can_grant_can_remove_signatory = 39;</code>
     */
    public static final int can_grant_can_remove_signatory_VALUE = 39;
    /**
     * <code>can_grant_can_transfer = 40;</code>
     */
    public static final int can_grant_can_transfer_VALUE = 40;
    /**
     * <code>can_grant_can_set_detail = 41;</code>
     */
    public static final int can_grant_can_set_detail_VALUE = 41;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RolePermission valueOf(int value) {
      return forNumber(value);
    }

    public static RolePermission forNumber(int value) {
      switch (value) {
        case 0: return can_append_role;
        case 1: return can_create_role;
        case 2: return can_detach_role;
        case 3: return can_add_asset_qty;
        case 4: return can_subtract_asset_qty;
        case 5: return can_add_peer;
        case 6: return can_add_signatory;
        case 7: return can_remove_signatory;
        case 8: return can_set_quorum;
        case 9: return can_create_account;
        case 10: return can_set_detail;
        case 11: return can_create_asset;
        case 12: return can_transfer;
        case 13: return can_receive;
        case 14: return can_create_domain;
        case 15: return can_read_assets;
        case 16: return can_get_roles;
        case 17: return can_get_my_account;
        case 18: return can_get_all_accounts;
        case 19: return can_get_domain_accounts;
        case 20: return can_get_my_signatories;
        case 21: return can_get_all_signatories;
        case 22: return can_get_domain_signatories;
        case 23: return can_get_my_acc_ast;
        case 24: return can_get_all_acc_ast;
        case 25: return can_get_domain_acc_ast;
        case 26: return can_get_my_acc_detail;
        case 27: return can_get_all_acc_detail;
        case 28: return can_get_domain_acc_detail;
        case 29: return can_get_my_acc_txs;
        case 30: return can_get_all_acc_txs;
        case 31: return can_get_domain_acc_txs;
        case 32: return can_get_my_acc_ast_txs;
        case 33: return can_get_all_acc_ast_txs;
        case 34: return can_get_domain_acc_ast_txs;
        case 35: return can_get_my_txs;
        case 36: return can_get_all_txs;
        case 37: return can_grant_can_set_quorum;
        case 38: return can_grant_can_add_signatory;
        case 39: return can_grant_can_remove_signatory;
        case 40: return can_grant_can_transfer;
        case 41: return can_grant_can_set_detail;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RolePermission>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RolePermission> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RolePermission>() {
            public RolePermission findValueByNumber(int number) {
              return RolePermission.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Primitive.getDescriptor().getEnumTypes().get(0);
    }

    private static final RolePermission[] VALUES = values();

    public static RolePermission valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RolePermission(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:iroha.protocol.RolePermission)
  }

  /**
   * Protobuf enum {@code iroha.protocol.GrantablePermission}
   */
  public enum GrantablePermission
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>can_add_my_signatory = 0;</code>
     */
    can_add_my_signatory(0),
    /**
     * <code>can_remove_my_signatory = 1;</code>
     */
    can_remove_my_signatory(1),
    /**
     * <code>can_set_my_quorum = 2;</code>
     */
    can_set_my_quorum(2),
    /**
     * <code>can_set_my_account_detail = 3;</code>
     */
    can_set_my_account_detail(3),
    /**
     * <pre>
     * not implemented now
     * </pre>
     *
     * <code>can_transfer_my_assets = 4;</code>
     */
    can_transfer_my_assets(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>can_add_my_signatory = 0;</code>
     */
    public static final int can_add_my_signatory_VALUE = 0;
    /**
     * <code>can_remove_my_signatory = 1;</code>
     */
    public static final int can_remove_my_signatory_VALUE = 1;
    /**
     * <code>can_set_my_quorum = 2;</code>
     */
    public static final int can_set_my_quorum_VALUE = 2;
    /**
     * <code>can_set_my_account_detail = 3;</code>
     */
    public static final int can_set_my_account_detail_VALUE = 3;
    /**
     * <pre>
     * not implemented now
     * </pre>
     *
     * <code>can_transfer_my_assets = 4;</code>
     */
    public static final int can_transfer_my_assets_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static GrantablePermission valueOf(int value) {
      return forNumber(value);
    }

    public static GrantablePermission forNumber(int value) {
      switch (value) {
        case 0: return can_add_my_signatory;
        case 1: return can_remove_my_signatory;
        case 2: return can_set_my_quorum;
        case 3: return can_set_my_account_detail;
        case 4: return can_transfer_my_assets;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GrantablePermission>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GrantablePermission> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GrantablePermission>() {
            public GrantablePermission findValueByNumber(int number) {
              return GrantablePermission.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Primitive.getDescriptor().getEnumTypes().get(1);
    }

    private static final GrantablePermission[] VALUES = values();

    public static GrantablePermission valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GrantablePermission(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:iroha.protocol.GrantablePermission)
  }

  public interface SignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.Signature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes pubkey = 1;</code>
     */
    com.google.protobuf.ByteString getPubkey();

    /**
     * <code>bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code iroha.protocol.Signature}
   */
  public  static final class Signature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.Signature)
      SignatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Signature.newBuilder() to construct.
    private Signature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Signature() {
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Signature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              pubkey_ = input.readBytes();
              break;
            }
            case 18: {

              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Primitive.internal_static_iroha_protocol_Signature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Primitive.internal_static_iroha_protocol_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Signature.class, Builder.class);
    }

    public static final int PUBKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <code>bytes pubkey = 1;</code>
     */
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!pubkey_.isEmpty()) {
        output.writeBytes(1, pubkey_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(2, signature_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!pubkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, pubkey_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Signature)) {
        return super.equals(obj);
      }
      Signature other = (Signature) obj;

      boolean result = true;
      result = result && getPubkey()
          .equals(other.getPubkey());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPubkey().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Signature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Signature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Signature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.Signature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.Signature)
        SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Primitive.internal_static_iroha_protocol_Signature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Primitive.internal_static_iroha_protocol_Signature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Signature.class, Builder.class);
      }

      // Construct using iroha.protocol.Primitive.Signature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pubkey_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Primitive.internal_static_iroha_protocol_Signature_descriptor;
      }

      public Signature getDefaultInstanceForType() {
        return Signature.getDefaultInstance();
      }

      public Signature build() {
        Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Signature buildPartial() {
        Signature result = new Signature(this);
        result.pubkey_ = pubkey_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Signature) {
          return mergeFrom((Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Signature other) {
        if (other == Signature.getDefaultInstance()) return this;
        if (other.getPubkey() != com.google.protobuf.ByteString.EMPTY) {
          setPubkey(other.getPubkey());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Signature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Signature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes pubkey = 1;</code>
       */
      public com.google.protobuf.ByteString getPubkey() {
        return pubkey_;
      }
      /**
       * <code>bytes pubkey = 1;</code>
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes pubkey = 1;</code>
       */
      public Builder clearPubkey() {
        
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.Signature)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.Signature)
    private static final Signature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Signature();
    }

    public static Signature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Signature>
        PARSER = new com.google.protobuf.AbstractParser<Signature>() {
      public Signature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Signature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Signature> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Signature> getParserForType() {
      return PARSER;
    }

    public Signature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface uint256OrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.uint256)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 first = 1;</code>
     */
    long getFirst();

    /**
     * <code>uint64 second = 2;</code>
     */
    long getSecond();

    /**
     * <code>uint64 third = 3;</code>
     */
    long getThird();

    /**
     * <code>uint64 fourth = 4;</code>
     */
    long getFourth();
  }
  /**
   * Protobuf type {@code iroha.protocol.uint256}
   */
  public  static final class uint256 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.uint256)
      uint256OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use uint256.newBuilder() to construct.
    private uint256(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private uint256() {
      first_ = 0L;
      second_ = 0L;
      third_ = 0L;
      fourth_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private uint256(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              first_ = input.readUInt64();
              break;
            }
            case 16: {

              second_ = input.readUInt64();
              break;
            }
            case 24: {

              third_ = input.readUInt64();
              break;
            }
            case 32: {

              fourth_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Primitive.internal_static_iroha_protocol_uint256_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Primitive.internal_static_iroha_protocol_uint256_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uint256.class, Builder.class);
    }

    public static final int FIRST_FIELD_NUMBER = 1;
    private long first_;
    /**
     * <code>uint64 first = 1;</code>
     */
    public long getFirst() {
      return first_;
    }

    public static final int SECOND_FIELD_NUMBER = 2;
    private long second_;
    /**
     * <code>uint64 second = 2;</code>
     */
    public long getSecond() {
      return second_;
    }

    public static final int THIRD_FIELD_NUMBER = 3;
    private long third_;
    /**
     * <code>uint64 third = 3;</code>
     */
    public long getThird() {
      return third_;
    }

    public static final int FOURTH_FIELD_NUMBER = 4;
    private long fourth_;
    /**
     * <code>uint64 fourth = 4;</code>
     */
    public long getFourth() {
      return fourth_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (first_ != 0L) {
        output.writeUInt64(1, first_);
      }
      if (second_ != 0L) {
        output.writeUInt64(2, second_);
      }
      if (third_ != 0L) {
        output.writeUInt64(3, third_);
      }
      if (fourth_ != 0L) {
        output.writeUInt64(4, fourth_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (first_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, first_);
      }
      if (second_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, second_);
      }
      if (third_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, third_);
      }
      if (fourth_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, fourth_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof uint256)) {
        return super.equals(obj);
      }
      uint256 other = (uint256) obj;

      boolean result = true;
      result = result && (getFirst()
          == other.getFirst());
      result = result && (getSecond()
          == other.getSecond());
      result = result && (getThird()
          == other.getThird());
      result = result && (getFourth()
          == other.getFourth());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFirst());
      hash = (37 * hash) + SECOND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSecond());
      hash = (37 * hash) + THIRD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getThird());
      hash = (37 * hash) + FOURTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFourth());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uint256 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uint256 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uint256 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uint256 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uint256 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uint256 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uint256 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uint256 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uint256 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uint256 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uint256 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uint256 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uint256 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.uint256}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.uint256)
        uint256OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Primitive.internal_static_iroha_protocol_uint256_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Primitive.internal_static_iroha_protocol_uint256_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uint256.class, Builder.class);
      }

      // Construct using iroha.protocol.Primitive.uint256.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        first_ = 0L;

        second_ = 0L;

        third_ = 0L;

        fourth_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Primitive.internal_static_iroha_protocol_uint256_descriptor;
      }

      public uint256 getDefaultInstanceForType() {
        return uint256.getDefaultInstance();
      }

      public uint256 build() {
        uint256 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uint256 buildPartial() {
        uint256 result = new uint256(this);
        result.first_ = first_;
        result.second_ = second_;
        result.third_ = third_;
        result.fourth_ = fourth_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uint256) {
          return mergeFrom((uint256)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uint256 other) {
        if (other == uint256.getDefaultInstance()) return this;
        if (other.getFirst() != 0L) {
          setFirst(other.getFirst());
        }
        if (other.getSecond() != 0L) {
          setSecond(other.getSecond());
        }
        if (other.getThird() != 0L) {
          setThird(other.getThird());
        }
        if (other.getFourth() != 0L) {
          setFourth(other.getFourth());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uint256 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uint256) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long first_ ;
      /**
       * <code>uint64 first = 1;</code>
       */
      public long getFirst() {
        return first_;
      }
      /**
       * <code>uint64 first = 1;</code>
       */
      public Builder setFirst(long value) {
        
        first_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 first = 1;</code>
       */
      public Builder clearFirst() {
        
        first_ = 0L;
        onChanged();
        return this;
      }

      private long second_ ;
      /**
       * <code>uint64 second = 2;</code>
       */
      public long getSecond() {
        return second_;
      }
      /**
       * <code>uint64 second = 2;</code>
       */
      public Builder setSecond(long value) {
        
        second_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 second = 2;</code>
       */
      public Builder clearSecond() {
        
        second_ = 0L;
        onChanged();
        return this;
      }

      private long third_ ;
      /**
       * <code>uint64 third = 3;</code>
       */
      public long getThird() {
        return third_;
      }
      /**
       * <code>uint64 third = 3;</code>
       */
      public Builder setThird(long value) {
        
        third_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 third = 3;</code>
       */
      public Builder clearThird() {
        
        third_ = 0L;
        onChanged();
        return this;
      }

      private long fourth_ ;
      /**
       * <code>uint64 fourth = 4;</code>
       */
      public long getFourth() {
        return fourth_;
      }
      /**
       * <code>uint64 fourth = 4;</code>
       */
      public Builder setFourth(long value) {
        
        fourth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 fourth = 4;</code>
       */
      public Builder clearFourth() {
        
        fourth_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.uint256)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.uint256)
    private static final uint256 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uint256();
    }

    public static uint256 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<uint256>
        PARSER = new com.google.protobuf.AbstractParser<uint256>() {
      public uint256 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new uint256(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<uint256> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<uint256> getParserForType() {
      return PARSER;
    }

    public uint256 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AmountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.Amount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.iroha.protocol.uint256 value = 1;</code>
     */
    boolean hasValue();
    /**
     * <code>.iroha.protocol.uint256 value = 1;</code>
     */
    uint256 getValue();
    /**
     * <code>.iroha.protocol.uint256 value = 1;</code>
     */
    uint256OrBuilder getValueOrBuilder();

    /**
     * <code>uint32 precision = 2;</code>
     */
    int getPrecision();
  }
  /**
   * Protobuf type {@code iroha.protocol.Amount}
   */
  public  static final class Amount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.Amount)
      AmountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Amount.newBuilder() to construct.
    private Amount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Amount() {
      precision_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Amount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              uint256.Builder subBuilder = null;
              if (value_ != null) {
                subBuilder = value_.toBuilder();
              }
              value_ = input.readMessage(uint256.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(value_);
                value_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              precision_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Primitive.internal_static_iroha_protocol_Amount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Primitive.internal_static_iroha_protocol_Amount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Amount.class, Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private uint256 value_;
    /**
     * <code>.iroha.protocol.uint256 value = 1;</code>
     */
    public boolean hasValue() {
      return value_ != null;
    }
    /**
     * <code>.iroha.protocol.uint256 value = 1;</code>
     */
    public uint256 getValue() {
      return value_ == null ? uint256.getDefaultInstance() : value_;
    }
    /**
     * <code>.iroha.protocol.uint256 value = 1;</code>
     */
    public uint256OrBuilder getValueOrBuilder() {
      return getValue();
    }

    public static final int PRECISION_FIELD_NUMBER = 2;
    private int precision_;
    /**
     * <code>uint32 precision = 2;</code>
     */
    public int getPrecision() {
      return precision_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != null) {
        output.writeMessage(1, getValue());
      }
      if (precision_ != 0) {
        output.writeUInt32(2, precision_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getValue());
      }
      if (precision_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, precision_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Amount)) {
        return super.equals(obj);
      }
      Amount other = (Amount) obj;

      boolean result = true;
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && (getPrecision()
          == other.getPrecision());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (37 * hash) + PRECISION_FIELD_NUMBER;
      hash = (53 * hash) + getPrecision();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Amount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Amount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Amount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Amount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Amount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Amount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Amount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Amount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Amount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Amount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Amount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Amount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Amount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.Amount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.Amount)
        AmountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Primitive.internal_static_iroha_protocol_Amount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Primitive.internal_static_iroha_protocol_Amount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Amount.class, Builder.class);
      }

      // Construct using iroha.protocol.Primitive.Amount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (valueBuilder_ == null) {
          value_ = null;
        } else {
          value_ = null;
          valueBuilder_ = null;
        }
        precision_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Primitive.internal_static_iroha_protocol_Amount_descriptor;
      }

      public Amount getDefaultInstanceForType() {
        return Amount.getDefaultInstance();
      }

      public Amount build() {
        Amount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Amount buildPartial() {
        Amount result = new Amount(this);
        if (valueBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        result.precision_ = precision_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Amount) {
          return mergeFrom((Amount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Amount other) {
        if (other == Amount.getDefaultInstance()) return this;
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        if (other.getPrecision() != 0) {
          setPrecision(other.getPrecision());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Amount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Amount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private uint256 value_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          uint256, uint256.Builder, uint256OrBuilder> valueBuilder_;
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public boolean hasValue() {
        return valueBuilder_ != null || value_ != null;
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public uint256 getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? uint256.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public Builder setValue(uint256 value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          valueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public Builder setValue(
          uint256.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public Builder mergeValue(uint256 value) {
        if (valueBuilder_ == null) {
          if (value_ != null) {
            value_ =
              uint256.newBuilder(value_).mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          valueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = null;
          onChanged();
        } else {
          value_ = null;
          valueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public uint256.Builder getValueBuilder() {
        
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      public uint256OrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              uint256.getDefaultInstance() : value_;
        }
      }
      /**
       * <code>.iroha.protocol.uint256 value = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          uint256, uint256.Builder, uint256OrBuilder>
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              uint256, uint256.Builder, uint256OrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }

      private int precision_ ;
      /**
       * <code>uint32 precision = 2;</code>
       */
      public int getPrecision() {
        return precision_;
      }
      /**
       * <code>uint32 precision = 2;</code>
       */
      public Builder setPrecision(int value) {
        
        precision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 precision = 2;</code>
       */
      public Builder clearPrecision() {
        
        precision_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.Amount)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.Amount)
    private static final Amount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Amount();
    }

    public static Amount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Amount>
        PARSER = new com.google.protobuf.AbstractParser<Amount>() {
      public Amount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Amount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Amount> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Amount> getParserForType() {
      return PARSER;
    }

    public Amount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iroha.protocol.Peer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1;</code>
     */
    String getAddress();
    /**
     * <code>string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>bytes peer_key = 2;</code>
     */
    com.google.protobuf.ByteString getPeerKey();
  }
  /**
   * Protobuf type {@code iroha.protocol.Peer}
   */
  public  static final class Peer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iroha.protocol.Peer)
      PeerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Peer.newBuilder() to construct.
    private Peer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Peer() {
      address_ = "";
      peerKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Peer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {

              peerKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Primitive.internal_static_iroha_protocol_Peer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Primitive.internal_static_iroha_protocol_Peer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Peer.class, Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile Object address_;
    /**
     * <code>string address = 1;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PEER_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString peerKey_;
    /**
     * <code>bytes peer_key = 2;</code>
     */
    public com.google.protobuf.ByteString getPeerKey() {
      return peerKey_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (!peerKey_.isEmpty()) {
        output.writeBytes(2, peerKey_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (!peerKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, peerKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Peer)) {
        return super.equals(obj);
      }
      Peer other = (Peer) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getPeerKey()
          .equals(other.getPeerKey());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PEER_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPeerKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Peer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Peer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Peer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Peer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Peer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Peer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Peer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Peer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Peer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Peer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Peer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Peer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Peer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iroha.protocol.Peer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iroha.protocol.Peer)
        PeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Primitive.internal_static_iroha_protocol_Peer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Primitive.internal_static_iroha_protocol_Peer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Peer.class, Builder.class);
      }

      // Construct using iroha.protocol.Primitive.Peer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        peerKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Primitive.internal_static_iroha_protocol_Peer_descriptor;
      }

      public Peer getDefaultInstanceForType() {
        return Peer.getDefaultInstance();
      }

      public Peer build() {
        Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Peer buildPartial() {
        Peer result = new Peer(this);
        result.address_ = address_;
        result.peerKey_ = peerKey_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Peer) {
          return mergeFrom((Peer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Peer other) {
        if (other == Peer.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getPeerKey() != com.google.protobuf.ByteString.EMPTY) {
          setPeerKey(other.getPeerKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Peer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Peer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object address_ = "";
      /**
       * <code>string address = 1;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString peerKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes peer_key = 2;</code>
       */
      public com.google.protobuf.ByteString getPeerKey() {
        return peerKey_;
      }
      /**
       * <code>bytes peer_key = 2;</code>
       */
      public Builder setPeerKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        peerKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes peer_key = 2;</code>
       */
      public Builder clearPeerKey() {
        
        peerKey_ = getDefaultInstance().getPeerKey();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iroha.protocol.Peer)
    }

    // @@protoc_insertion_point(class_scope:iroha.protocol.Peer)
    private static final Peer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Peer();
    }

    public static Peer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Peer>
        PARSER = new com.google.protobuf.AbstractParser<Peer>() {
      public Peer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Peer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Peer> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Peer> getParserForType() {
      return PARSER;
    }

    public Peer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_Signature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_Signature_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_uint256_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_uint256_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_Amount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_Amount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iroha_protocol_Peer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iroha_protocol_Peer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017primitive.proto\022\016iroha.protocol\".\n\tSig" +
      "nature\022\016\n\006pubkey\030\001 \001(\014\022\021\n\tsignature\030\002 \001(" +
      "\014\"G\n\007uint256\022\r\n\005first\030\001 \001(\004\022\016\n\006second\030\002 " +
      "\001(\004\022\r\n\005third\030\003 \001(\004\022\016\n\006fourth\030\004 \001(\004\"C\n\006Am" +
      "ount\022&\n\005value\030\001 \001(\0132\027.iroha.protocol.uin" +
      "t256\022\021\n\tprecision\030\002 \001(\r\")\n\004Peer\022\017\n\007addre" +
      "ss\030\001 \001(\t\022\020\n\010peer_key\030\002 \001(\014*\264\010\n\016RolePermi" +
      "ssion\022\023\n\017can_append_role\020\000\022\023\n\017can_create" +
      "_role\020\001\022\023\n\017can_detach_role\020\002\022\025\n\021can_add_" +
      "asset_qty\020\003\022\032\n\026can_subtract_asset_qty\020\004\022" +
      "\020\n\014can_add_peer\020\005\022\025\n\021can_add_signatory\020\006" +
      "\022\030\n\024can_remove_signatory\020\007\022\022\n\016can_set_qu" +
      "orum\020\010\022\026\n\022can_create_account\020\t\022\022\n\016can_se" +
      "t_detail\020\n\022\024\n\020can_create_asset\020\013\022\020\n\014can_" +
      "transfer\020\014\022\017\n\013can_receive\020\r\022\025\n\021can_creat" +
      "e_domain\020\016\022\023\n\017can_read_assets\020\017\022\021\n\rcan_g" +
      "et_roles\020\020\022\026\n\022can_get_my_account\020\021\022\030\n\024ca" +
      "n_get_all_accounts\020\022\022\033\n\027can_get_domain_a" +
      "ccounts\020\023\022\032\n\026can_get_my_signatories\020\024\022\033\n" +
      "\027can_get_all_signatories\020\025\022\036\n\032can_get_do" +
      "main_signatories\020\026\022\026\n\022can_get_my_acc_ast" +
      "\020\027\022\027\n\023can_get_all_acc_ast\020\030\022\032\n\026can_get_d" +
      "omain_acc_ast\020\031\022\031\n\025can_get_my_acc_detail" +
      "\020\032\022\032\n\026can_get_all_acc_detail\020\033\022\035\n\031can_ge" +
      "t_domain_acc_detail\020\034\022\026\n\022can_get_my_acc_" +
      "txs\020\035\022\027\n\023can_get_all_acc_txs\020\036\022\032\n\026can_ge" +
      "t_domain_acc_txs\020\037\022\032\n\026can_get_my_acc_ast" +
      "_txs\020 \022\033\n\027can_get_all_acc_ast_txs\020!\022\036\n\032c" +
      "an_get_domain_acc_ast_txs\020\"\022\022\n\016can_get_m" +
      "y_txs\020#\022\023\n\017can_get_all_txs\020$\022\034\n\030can_gran" +
      "t_can_set_quorum\020%\022\037\n\033can_grant_can_add_" +
      "signatory\020&\022\"\n\036can_grant_can_remove_sign" +
      "atory\020\'\022\032\n\026can_grant_can_transfer\020(\022\034\n\030c" +
      "an_grant_can_set_detail\020)*\236\001\n\023GrantableP" +
      "ermission\022\030\n\024can_add_my_signatory\020\000\022\033\n\027c" +
      "an_remove_my_signatory\020\001\022\025\n\021can_set_my_q" +
      "uorum\020\002\022\035\n\031can_set_my_account_detail\020\003\022\032" +
      "\n\026can_transfer_my_assets\020\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_iroha_protocol_Signature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iroha_protocol_Signature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_Signature_descriptor,
        new String[] { "Pubkey", "Signature", });
    internal_static_iroha_protocol_uint256_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iroha_protocol_uint256_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_uint256_descriptor,
        new String[] { "First", "Second", "Third", "Fourth", });
    internal_static_iroha_protocol_Amount_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_iroha_protocol_Amount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_Amount_descriptor,
        new String[] { "Value", "Precision", });
    internal_static_iroha_protocol_Peer_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_iroha_protocol_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iroha_protocol_Peer_descriptor,
        new String[] { "Address", "PeerKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
