// Generated by the protocol buffer compiler.  DO NOT EDIT!

package iroha.protocol.nano;

@SuppressWarnings("hiding")
public interface Commands {

  public static final class AddAssetQuantity extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AddAssetQuantity[] _emptyArray;
    public static AddAssetQuantity[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AddAssetQuantity[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string asset_id = 2;
    public String assetId;

    // .iroha.protocol.Amount amount = 3;
    public iroha.protocol.nano.Primitive.Amount amount;

    public AddAssetQuantity() {
      clear();
    }

    public AddAssetQuantity clear() {
      accountId = "";
      assetId = "";
      amount = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        output.writeString(2, this.assetId);
      }
      if (this.amount != null) {
        output.writeMessage(3, this.amount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.assetId);
      }
      if (this.amount != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.amount);
      }
      return size;
    }

    @Override
    public AddAssetQuantity mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.assetId = input.readString();
            break;
          }
          case 26: {
            if (this.amount == null) {
              this.amount = new iroha.protocol.nano.Primitive.Amount();
            }
            input.readMessage(this.amount);
            break;
          }
        }
      }
    }

    public static AddAssetQuantity parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AddAssetQuantity(), data);
    }

    public static AddAssetQuantity parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AddAssetQuantity().mergeFrom(input);
    }
  }

  public static final class AddPeer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AddPeer[] _emptyArray;
    public static AddPeer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AddPeer[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.Peer peer = 1;
    public iroha.protocol.nano.Primitive.Peer peer;

    public AddPeer() {
      clear();
    }

    public AddPeer clear() {
      peer = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.peer != null) {
        output.writeMessage(1, this.peer);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.peer != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.peer);
      }
      return size;
    }

    @Override
    public AddPeer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.peer == null) {
              this.peer = new iroha.protocol.nano.Primitive.Peer();
            }
            input.readMessage(this.peer);
            break;
          }
        }
      }
    }

    public static AddPeer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AddPeer(), data);
    }

    public static AddPeer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AddPeer().mergeFrom(input);
    }
  }

  public static final class AddSignatory extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AddSignatory[] _emptyArray;
    public static AddSignatory[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AddSignatory[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // bytes public_key = 2;
    public byte[] publicKey;

    public AddSignatory() {
      clear();
    }

    public AddSignatory clear() {
      accountId = "";
      publicKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.publicKey);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.publicKey);
      }
      return size;
    }

    @Override
    public AddSignatory mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.publicKey = input.readBytes();
            break;
          }
        }
      }
    }

    public static AddSignatory parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AddSignatory(), data);
    }

    public static AddSignatory parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AddSignatory().mergeFrom(input);
    }
  }

  public static final class CreateAsset extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CreateAsset[] _emptyArray;
    public static CreateAsset[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CreateAsset[0];
          }
        }
      }
      return _emptyArray;
    }

    // string asset_name = 1;
    public String assetName;

    // string domain_id = 2;
    public String domainId;

    // uint32 precision = 3;
    public int precision;

    public CreateAsset() {
      clear();
    }

    public CreateAsset clear() {
      assetName = "";
      domainId = "";
      precision = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.assetName.equals("")) {
        output.writeString(1, this.assetName);
      }
      if (!this.domainId.equals("")) {
        output.writeString(2, this.domainId);
      }
      if (this.precision != 0) {
        output.writeUInt32(3, this.precision);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.assetName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.assetName);
      }
      if (!this.domainId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.domainId);
      }
      if (this.precision != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.precision);
      }
      return size;
    }

    @Override
    public CreateAsset mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.assetName = input.readString();
            break;
          }
          case 18: {
            this.domainId = input.readString();
            break;
          }
          case 24: {
            this.precision = input.readUInt32();
            break;
          }
        }
      }
    }

    public static CreateAsset parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CreateAsset(), data);
    }

    public static CreateAsset parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CreateAsset().mergeFrom(input);
    }
  }

  public static final class CreateAccount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CreateAccount[] _emptyArray;
    public static CreateAccount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CreateAccount[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_name = 1;
    public String accountName;

    // string domain_id = 2;
    public String domainId;

    // bytes main_pubkey = 3;
    public byte[] mainPubkey;

    public CreateAccount() {
      clear();
    }

    public CreateAccount clear() {
      accountName = "";
      domainId = "";
      mainPubkey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountName.equals("")) {
        output.writeString(1, this.accountName);
      }
      if (!this.domainId.equals("")) {
        output.writeString(2, this.domainId);
      }
      if (!java.util.Arrays.equals(this.mainPubkey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(3, this.mainPubkey);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountName);
      }
      if (!this.domainId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.domainId);
      }
      if (!java.util.Arrays.equals(this.mainPubkey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.mainPubkey);
      }
      return size;
    }

    @Override
    public CreateAccount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountName = input.readString();
            break;
          }
          case 18: {
            this.domainId = input.readString();
            break;
          }
          case 26: {
            this.mainPubkey = input.readBytes();
            break;
          }
        }
      }
    }

    public static CreateAccount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CreateAccount(), data);
    }

    public static CreateAccount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CreateAccount().mergeFrom(input);
    }
  }

  public static final class SetAccountDetail extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SetAccountDetail[] _emptyArray;
    public static SetAccountDetail[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SetAccountDetail[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string key = 2;
    public String key;

    // string value = 3;
    public String value;

    public SetAccountDetail() {
      clear();
    }

    public SetAccountDetail clear() {
      accountId = "";
      key = "";
      value = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.key.equals("")) {
        output.writeString(2, this.key);
      }
      if (!this.value.equals("")) {
        output.writeString(3, this.value);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.key.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.key);
      }
      if (!this.value.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.value);
      }
      return size;
    }

    @Override
    public SetAccountDetail mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.key = input.readString();
            break;
          }
          case 26: {
            this.value = input.readString();
            break;
          }
        }
      }
    }

    public static SetAccountDetail parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SetAccountDetail(), data);
    }

    public static SetAccountDetail parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SetAccountDetail().mergeFrom(input);
    }
  }

  public static final class CreateDomain extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CreateDomain[] _emptyArray;
    public static CreateDomain[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CreateDomain[0];
          }
        }
      }
      return _emptyArray;
    }

    // string domain_id = 1;
    public String domainId;

    // string default_role = 2;
    public String defaultRole;

    public CreateDomain() {
      clear();
    }

    public CreateDomain clear() {
      domainId = "";
      defaultRole = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.domainId.equals("")) {
        output.writeString(1, this.domainId);
      }
      if (!this.defaultRole.equals("")) {
        output.writeString(2, this.defaultRole);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.domainId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.domainId);
      }
      if (!this.defaultRole.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.defaultRole);
      }
      return size;
    }

    @Override
    public CreateDomain mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.domainId = input.readString();
            break;
          }
          case 18: {
            this.defaultRole = input.readString();
            break;
          }
        }
      }
    }

    public static CreateDomain parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CreateDomain(), data);
    }

    public static CreateDomain parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CreateDomain().mergeFrom(input);
    }
  }

  public static final class RemoveSignatory extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RemoveSignatory[] _emptyArray;
    public static RemoveSignatory[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RemoveSignatory[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // bytes public_key = 2;
    public byte[] publicKey;

    public RemoveSignatory() {
      clear();
    }

    public RemoveSignatory clear() {
      accountId = "";
      publicKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.publicKey);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!java.util.Arrays.equals(this.publicKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.publicKey);
      }
      return size;
    }

    @Override
    public RemoveSignatory mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.publicKey = input.readBytes();
            break;
          }
        }
      }
    }

    public static RemoveSignatory parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RemoveSignatory(), data);
    }

    public static RemoveSignatory parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RemoveSignatory().mergeFrom(input);
    }
  }

  public static final class SetAccountQuorum extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SetAccountQuorum[] _emptyArray;
    public static SetAccountQuorum[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SetAccountQuorum[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // uint32 quorum = 2;
    public int quorum;

    public SetAccountQuorum() {
      clear();
    }

    public SetAccountQuorum clear() {
      accountId = "";
      quorum = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (this.quorum != 0) {
        output.writeUInt32(2, this.quorum);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (this.quorum != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.quorum);
      }
      return size;
    }

    @Override
    public SetAccountQuorum mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 16: {
            this.quorum = input.readUInt32();
            break;
          }
        }
      }
    }

    public static SetAccountQuorum parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SetAccountQuorum(), data);
    }

    public static SetAccountQuorum parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SetAccountQuorum().mergeFrom(input);
    }
  }

  public static final class TransferAsset extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TransferAsset[] _emptyArray;
    public static TransferAsset[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TransferAsset[0];
          }
        }
      }
      return _emptyArray;
    }

    // string src_account_id = 1;
    public String srcAccountId;

    // string dest_account_id = 2;
    public String destAccountId;

    // string asset_id = 3;
    public String assetId;

    // string description = 4;
    public String description;

    // .iroha.protocol.Amount amount = 5;
    public iroha.protocol.nano.Primitive.Amount amount;

    public TransferAsset() {
      clear();
    }

    public TransferAsset clear() {
      srcAccountId = "";
      destAccountId = "";
      assetId = "";
      description = "";
      amount = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.srcAccountId.equals("")) {
        output.writeString(1, this.srcAccountId);
      }
      if (!this.destAccountId.equals("")) {
        output.writeString(2, this.destAccountId);
      }
      if (!this.assetId.equals("")) {
        output.writeString(3, this.assetId);
      }
      if (!this.description.equals("")) {
        output.writeString(4, this.description);
      }
      if (this.amount != null) {
        output.writeMessage(5, this.amount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.srcAccountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.srcAccountId);
      }
      if (!this.destAccountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.destAccountId);
      }
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.assetId);
      }
      if (!this.description.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.description);
      }
      if (this.amount != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5, this.amount);
      }
      return size;
    }

    @Override
    public TransferAsset mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.srcAccountId = input.readString();
            break;
          }
          case 18: {
            this.destAccountId = input.readString();
            break;
          }
          case 26: {
            this.assetId = input.readString();
            break;
          }
          case 34: {
            this.description = input.readString();
            break;
          }
          case 42: {
            if (this.amount == null) {
              this.amount = new iroha.protocol.nano.Primitive.Amount();
            }
            input.readMessage(this.amount);
            break;
          }
        }
      }
    }

    public static TransferAsset parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TransferAsset(), data);
    }

    public static TransferAsset parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TransferAsset().mergeFrom(input);
    }
  }

  public static final class AppendRole extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AppendRole[] _emptyArray;
    public static AppendRole[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AppendRole[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string role_name = 2;
    public String roleName;

    public AppendRole() {
      clear();
    }

    public AppendRole clear() {
      accountId = "";
      roleName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.roleName.equals("")) {
        output.writeString(2, this.roleName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.roleName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.roleName);
      }
      return size;
    }

    @Override
    public AppendRole mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.roleName = input.readString();
            break;
          }
        }
      }
    }

    public static AppendRole parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AppendRole(), data);
    }

    public static AppendRole parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AppendRole().mergeFrom(input);
    }
  }

  public static final class DetachRole extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DetachRole[] _emptyArray;
    public static DetachRole[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DetachRole[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string role_name = 2;
    public String roleName;

    public DetachRole() {
      clear();
    }

    public DetachRole clear() {
      accountId = "";
      roleName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.roleName.equals("")) {
        output.writeString(2, this.roleName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.roleName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.roleName);
      }
      return size;
    }

    @Override
    public DetachRole mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.roleName = input.readString();
            break;
          }
        }
      }
    }

    public static DetachRole parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DetachRole(), data);
    }

    public static DetachRole parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DetachRole().mergeFrom(input);
    }
  }

  public static final class CreateRole extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CreateRole[] _emptyArray;
    public static CreateRole[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CreateRole[0];
          }
        }
      }
      return _emptyArray;
    }

    // string role_name = 1;
    public String roleName;

    // repeated .iroha.protocol.RolePermission permissions = 2;
    public int[] permissions;

    public CreateRole() {
      clear();
    }

    public CreateRole clear() {
      roleName = "";
      permissions = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.roleName.equals("")) {
        output.writeString(1, this.roleName);
      }
      if (this.permissions != null && this.permissions.length > 0) {
        for (int i = 0; i < this.permissions.length; i++) {
          output.writeInt32(2, this.permissions[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.roleName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.roleName);
      }
      if (this.permissions != null && this.permissions.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.permissions.length; i++) {
          int element = this.permissions[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.permissions.length;
      }
      return size;
    }

    @Override
    public CreateRole mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.roleName = input.readString();
            break;
          }
          case 16: {
            int length = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 16);
            int[] validValues = new int[length];
            int validCount = 0;
            for (int i = 0; i < length; i++) {
              if (i != 0) { // tag for first value already consumed.
                input.readTag();
              }
              int value = input.readInt32();
              switch (value) {
                case iroha.protocol.nano.Primitive.can_append_role:
                case iroha.protocol.nano.Primitive.can_create_role:
                case iroha.protocol.nano.Primitive.can_detach_role:
                case iroha.protocol.nano.Primitive.can_add_asset_qty:
                case iroha.protocol.nano.Primitive.can_subtract_asset_qty:
                case iroha.protocol.nano.Primitive.can_add_peer:
                case iroha.protocol.nano.Primitive.can_add_signatory:
                case iroha.protocol.nano.Primitive.can_remove_signatory:
                case iroha.protocol.nano.Primitive.can_set_quorum:
                case iroha.protocol.nano.Primitive.can_create_account:
                case iroha.protocol.nano.Primitive.can_set_detail:
                case iroha.protocol.nano.Primitive.can_create_asset:
                case iroha.protocol.nano.Primitive.can_transfer:
                case iroha.protocol.nano.Primitive.can_receive:
                case iroha.protocol.nano.Primitive.can_create_domain:
                case iroha.protocol.nano.Primitive.can_read_assets:
                case iroha.protocol.nano.Primitive.can_get_roles:
                case iroha.protocol.nano.Primitive.can_get_my_account:
                case iroha.protocol.nano.Primitive.can_get_all_accounts:
                case iroha.protocol.nano.Primitive.can_get_domain_accounts:
                case iroha.protocol.nano.Primitive.can_get_my_signatories:
                case iroha.protocol.nano.Primitive.can_get_all_signatories:
                case iroha.protocol.nano.Primitive.can_get_domain_signatories:
                case iroha.protocol.nano.Primitive.can_get_my_acc_ast:
                case iroha.protocol.nano.Primitive.can_get_all_acc_ast:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_ast:
                case iroha.protocol.nano.Primitive.can_get_my_acc_detail:
                case iroha.protocol.nano.Primitive.can_get_all_acc_detail:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_detail:
                case iroha.protocol.nano.Primitive.can_get_my_acc_txs:
                case iroha.protocol.nano.Primitive.can_get_all_acc_txs:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_txs:
                case iroha.protocol.nano.Primitive.can_get_my_acc_ast_txs:
                case iroha.protocol.nano.Primitive.can_get_all_acc_ast_txs:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_ast_txs:
                case iroha.protocol.nano.Primitive.can_get_my_txs:
                case iroha.protocol.nano.Primitive.can_get_all_txs:
                case iroha.protocol.nano.Primitive.can_grant_can_set_quorum:
                case iroha.protocol.nano.Primitive.can_grant_can_add_signatory:
                case iroha.protocol.nano.Primitive.can_grant_can_remove_signatory:
                case iroha.protocol.nano.Primitive.can_grant_can_transfer:
                case iroha.protocol.nano.Primitive.can_grant_can_set_detail:
                  validValues[validCount++] = value;
                  break;
              }
            }
            if (validCount != 0) {
              int i = this.permissions == null ? 0 : this.permissions.length;
              if (i == 0 && validCount == validValues.length) {
                this.permissions = validValues;
              } else {
                int[] newArray = new int[i + validCount];
                if (i != 0) {
                  System.arraycopy(this.permissions, 0, newArray, 0, i);
                }
                System.arraycopy(validValues, 0, newArray, i, validCount);
                this.permissions = newArray;
              }
            }
            break;
          }
          case 18: {
            int bytes = input.readRawVarint32();
            int limit = input.pushLimit(bytes);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              switch (input.readInt32()) {
                case iroha.protocol.nano.Primitive.can_append_role:
                case iroha.protocol.nano.Primitive.can_create_role:
                case iroha.protocol.nano.Primitive.can_detach_role:
                case iroha.protocol.nano.Primitive.can_add_asset_qty:
                case iroha.protocol.nano.Primitive.can_subtract_asset_qty:
                case iroha.protocol.nano.Primitive.can_add_peer:
                case iroha.protocol.nano.Primitive.can_add_signatory:
                case iroha.protocol.nano.Primitive.can_remove_signatory:
                case iroha.protocol.nano.Primitive.can_set_quorum:
                case iroha.protocol.nano.Primitive.can_create_account:
                case iroha.protocol.nano.Primitive.can_set_detail:
                case iroha.protocol.nano.Primitive.can_create_asset:
                case iroha.protocol.nano.Primitive.can_transfer:
                case iroha.protocol.nano.Primitive.can_receive:
                case iroha.protocol.nano.Primitive.can_create_domain:
                case iroha.protocol.nano.Primitive.can_read_assets:
                case iroha.protocol.nano.Primitive.can_get_roles:
                case iroha.protocol.nano.Primitive.can_get_my_account:
                case iroha.protocol.nano.Primitive.can_get_all_accounts:
                case iroha.protocol.nano.Primitive.can_get_domain_accounts:
                case iroha.protocol.nano.Primitive.can_get_my_signatories:
                case iroha.protocol.nano.Primitive.can_get_all_signatories:
                case iroha.protocol.nano.Primitive.can_get_domain_signatories:
                case iroha.protocol.nano.Primitive.can_get_my_acc_ast:
                case iroha.protocol.nano.Primitive.can_get_all_acc_ast:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_ast:
                case iroha.protocol.nano.Primitive.can_get_my_acc_detail:
                case iroha.protocol.nano.Primitive.can_get_all_acc_detail:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_detail:
                case iroha.protocol.nano.Primitive.can_get_my_acc_txs:
                case iroha.protocol.nano.Primitive.can_get_all_acc_txs:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_txs:
                case iroha.protocol.nano.Primitive.can_get_my_acc_ast_txs:
                case iroha.protocol.nano.Primitive.can_get_all_acc_ast_txs:
                case iroha.protocol.nano.Primitive.can_get_domain_acc_ast_txs:
                case iroha.protocol.nano.Primitive.can_get_my_txs:
                case iroha.protocol.nano.Primitive.can_get_all_txs:
                case iroha.protocol.nano.Primitive.can_grant_can_set_quorum:
                case iroha.protocol.nano.Primitive.can_grant_can_add_signatory:
                case iroha.protocol.nano.Primitive.can_grant_can_remove_signatory:
                case iroha.protocol.nano.Primitive.can_grant_can_transfer:
                case iroha.protocol.nano.Primitive.can_grant_can_set_detail:
                  arrayLength++;
                  break;
              }
            }
            if (arrayLength != 0) {
              input.rewindToPosition(startPos);
              int i = this.permissions == null ? 0 : this.permissions.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                System.arraycopy(this.permissions, 0, newArray, 0, i);
              }
              while (input.getBytesUntilLimit() > 0) {
                int value = input.readInt32();
                switch (value) {
                  case iroha.protocol.nano.Primitive.can_append_role:
                  case iroha.protocol.nano.Primitive.can_create_role:
                  case iroha.protocol.nano.Primitive.can_detach_role:
                  case iroha.protocol.nano.Primitive.can_add_asset_qty:
                  case iroha.protocol.nano.Primitive.can_subtract_asset_qty:
                  case iroha.protocol.nano.Primitive.can_add_peer:
                  case iroha.protocol.nano.Primitive.can_add_signatory:
                  case iroha.protocol.nano.Primitive.can_remove_signatory:
                  case iroha.protocol.nano.Primitive.can_set_quorum:
                  case iroha.protocol.nano.Primitive.can_create_account:
                  case iroha.protocol.nano.Primitive.can_set_detail:
                  case iroha.protocol.nano.Primitive.can_create_asset:
                  case iroha.protocol.nano.Primitive.can_transfer:
                  case iroha.protocol.nano.Primitive.can_receive:
                  case iroha.protocol.nano.Primitive.can_create_domain:
                  case iroha.protocol.nano.Primitive.can_read_assets:
                  case iroha.protocol.nano.Primitive.can_get_roles:
                  case iroha.protocol.nano.Primitive.can_get_my_account:
                  case iroha.protocol.nano.Primitive.can_get_all_accounts:
                  case iroha.protocol.nano.Primitive.can_get_domain_accounts:
                  case iroha.protocol.nano.Primitive.can_get_my_signatories:
                  case iroha.protocol.nano.Primitive.can_get_all_signatories:
                  case iroha.protocol.nano.Primitive.can_get_domain_signatories:
                  case iroha.protocol.nano.Primitive.can_get_my_acc_ast:
                  case iroha.protocol.nano.Primitive.can_get_all_acc_ast:
                  case iroha.protocol.nano.Primitive.can_get_domain_acc_ast:
                  case iroha.protocol.nano.Primitive.can_get_my_acc_detail:
                  case iroha.protocol.nano.Primitive.can_get_all_acc_detail:
                  case iroha.protocol.nano.Primitive.can_get_domain_acc_detail:
                  case iroha.protocol.nano.Primitive.can_get_my_acc_txs:
                  case iroha.protocol.nano.Primitive.can_get_all_acc_txs:
                  case iroha.protocol.nano.Primitive.can_get_domain_acc_txs:
                  case iroha.protocol.nano.Primitive.can_get_my_acc_ast_txs:
                  case iroha.protocol.nano.Primitive.can_get_all_acc_ast_txs:
                  case iroha.protocol.nano.Primitive.can_get_domain_acc_ast_txs:
                  case iroha.protocol.nano.Primitive.can_get_my_txs:
                  case iroha.protocol.nano.Primitive.can_get_all_txs:
                  case iroha.protocol.nano.Primitive.can_grant_can_set_quorum:
                  case iroha.protocol.nano.Primitive.can_grant_can_add_signatory:
                  case iroha.protocol.nano.Primitive.can_grant_can_remove_signatory:
                  case iroha.protocol.nano.Primitive.can_grant_can_transfer:
                  case iroha.protocol.nano.Primitive.can_grant_can_set_detail:
                    newArray[i++] = value;
                    break;
                }
              }
              this.permissions = newArray;
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static CreateRole parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CreateRole(), data);
    }

    public static CreateRole parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CreateRole().mergeFrom(input);
    }
  }

  public static final class GrantPermission extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GrantPermission[] _emptyArray;
    public static GrantPermission[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GrantPermission[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // .iroha.protocol.GrantablePermission permission = 2;
    public int permission;

    public GrantPermission() {
      clear();
    }

    public GrantPermission clear() {
      accountId = "";
      permission = iroha.protocol.nano.Primitive.can_add_my_signatory;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (this.permission != iroha.protocol.nano.Primitive.can_add_my_signatory) {
        output.writeInt32(2, this.permission);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (this.permission != iroha.protocol.nano.Primitive.can_add_my_signatory) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, this.permission);
      }
      return size;
    }

    @Override
    public GrantPermission mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case iroha.protocol.nano.Primitive.can_add_my_signatory:
              case iroha.protocol.nano.Primitive.can_remove_my_signatory:
              case iroha.protocol.nano.Primitive.can_set_my_quorum:
              case iroha.protocol.nano.Primitive.can_set_my_account_detail:
              case iroha.protocol.nano.Primitive.can_transfer_my_assets:
                this.permission = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static GrantPermission parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GrantPermission(), data);
    }

    public static GrantPermission parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GrantPermission().mergeFrom(input);
    }
  }

  public static final class RevokePermission extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RevokePermission[] _emptyArray;
    public static RevokePermission[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RevokePermission[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // .iroha.protocol.GrantablePermission permission = 2;
    public int permission;

    public RevokePermission() {
      clear();
    }

    public RevokePermission clear() {
      accountId = "";
      permission = iroha.protocol.nano.Primitive.can_add_my_signatory;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (this.permission != iroha.protocol.nano.Primitive.can_add_my_signatory) {
        output.writeInt32(2, this.permission);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (this.permission != iroha.protocol.nano.Primitive.can_add_my_signatory) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, this.permission);
      }
      return size;
    }

    @Override
    public RevokePermission mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case iroha.protocol.nano.Primitive.can_add_my_signatory:
              case iroha.protocol.nano.Primitive.can_remove_my_signatory:
              case iroha.protocol.nano.Primitive.can_set_my_quorum:
              case iroha.protocol.nano.Primitive.can_set_my_account_detail:
              case iroha.protocol.nano.Primitive.can_transfer_my_assets:
                this.permission = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static RevokePermission parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RevokePermission(), data);
    }

    public static RevokePermission parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RevokePermission().mergeFrom(input);
    }
  }

  public static final class SubtractAssetQuantity extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SubtractAssetQuantity[] _emptyArray;
    public static SubtractAssetQuantity[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SubtractAssetQuantity[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string asset_id = 2;
    public String assetId;

    // .iroha.protocol.Amount amount = 3;
    public iroha.protocol.nano.Primitive.Amount amount;

    public SubtractAssetQuantity() {
      clear();
    }

    public SubtractAssetQuantity clear() {
      accountId = "";
      assetId = "";
      amount = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        output.writeString(2, this.assetId);
      }
      if (this.amount != null) {
        output.writeMessage(3, this.amount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.assetId);
      }
      if (this.amount != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.amount);
      }
      return size;
    }

    @Override
    public SubtractAssetQuantity mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.assetId = input.readString();
            break;
          }
          case 26: {
            if (this.amount == null) {
              this.amount = new iroha.protocol.nano.Primitive.Amount();
            }
            input.readMessage(this.amount);
            break;
          }
        }
      }
    }

    public static SubtractAssetQuantity parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SubtractAssetQuantity(), data);
    }

    public static SubtractAssetQuantity parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SubtractAssetQuantity().mergeFrom(input);
    }
  }

  public static final class Command extends
      com.google.protobuf.nano.MessageNano {
    public static final int ADD_ASSET_QUANTITY_FIELD_NUMBER = 1;
    public static final int ADD_PEER_FIELD_NUMBER = 2;
    public static final int ADD_SIGNATORY_FIELD_NUMBER = 3;
    public static final int APPEND_ROLE_FIELD_NUMBER = 4;
    public static final int CREATE_ACCOUNT_FIELD_NUMBER = 5;
    public static final int CREATE_ASSET_FIELD_NUMBER = 6;
    public static final int CREATE_DOMAIN_FIELD_NUMBER = 7;
    public static final int CREATE_ROLE_FIELD_NUMBER = 8;
    public static final int DETACH_ROLE_FIELD_NUMBER = 9;
    public static final int GRANT_PERMISSION_FIELD_NUMBER = 10;
    public static final int REMOVE_SIGN_FIELD_NUMBER = 11;
    public static final int REVOKE_PERMISSION_FIELD_NUMBER = 12;
    public static final int SET_ACCOUNT_DETAIL_FIELD_NUMBER = 13;
    public static final int SET_QUORUM_FIELD_NUMBER = 14;
    public static final int SUBTRACT_ASSET_QUANTITY_FIELD_NUMBER = 15;
    public static final int TRANSFER_ASSET_FIELD_NUMBER = 16;
    private int commandCase_ = 0;
    private Object command_;
    public int getCommandCase() {
      return this.commandCase_;
    }
    public Command clearCommand() {
      this.commandCase_ = 0;
      this.command_ = null;
      return this;
    }

    private static volatile Command[] _emptyArray;
    public static Command[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Command[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.AddAssetQuantity add_asset_quantity = 1;
    public boolean hasAddAssetQuantity() {
      return this.commandCase_ == 1;
    }
    public iroha.protocol.nano.Commands.AddAssetQuantity getAddAssetQuantity() {
      if (this.commandCase_ == 1) {
        return (iroha.protocol.nano.Commands.AddAssetQuantity) this.command_;
      }
      return null;
    }
    public Command setAddAssetQuantity(iroha.protocol.nano.Commands.AddAssetQuantity value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 1;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.AddPeer add_peer = 2;
    public boolean hasAddPeer() {
      return this.commandCase_ == 2;
    }
    public iroha.protocol.nano.Commands.AddPeer getAddPeer() {
      if (this.commandCase_ == 2) {
        return (iroha.protocol.nano.Commands.AddPeer) this.command_;
      }
      return null;
    }
    public Command setAddPeer(iroha.protocol.nano.Commands.AddPeer value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 2;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.AddSignatory add_signatory = 3;
    public boolean hasAddSignatory() {
      return this.commandCase_ == 3;
    }
    public iroha.protocol.nano.Commands.AddSignatory getAddSignatory() {
      if (this.commandCase_ == 3) {
        return (iroha.protocol.nano.Commands.AddSignatory) this.command_;
      }
      return null;
    }
    public Command setAddSignatory(iroha.protocol.nano.Commands.AddSignatory value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 3;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.AppendRole append_role = 4;
    public boolean hasAppendRole() {
      return this.commandCase_ == 4;
    }
    public iroha.protocol.nano.Commands.AppendRole getAppendRole() {
      if (this.commandCase_ == 4) {
        return (iroha.protocol.nano.Commands.AppendRole) this.command_;
      }
      return null;
    }
    public Command setAppendRole(iroha.protocol.nano.Commands.AppendRole value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 4;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.CreateAccount create_account = 5;
    public boolean hasCreateAccount() {
      return this.commandCase_ == 5;
    }
    public iroha.protocol.nano.Commands.CreateAccount getCreateAccount() {
      if (this.commandCase_ == 5) {
        return (iroha.protocol.nano.Commands.CreateAccount) this.command_;
      }
      return null;
    }
    public Command setCreateAccount(iroha.protocol.nano.Commands.CreateAccount value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 5;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.CreateAsset create_asset = 6;
    public boolean hasCreateAsset() {
      return this.commandCase_ == 6;
    }
    public iroha.protocol.nano.Commands.CreateAsset getCreateAsset() {
      if (this.commandCase_ == 6) {
        return (iroha.protocol.nano.Commands.CreateAsset) this.command_;
      }
      return null;
    }
    public Command setCreateAsset(iroha.protocol.nano.Commands.CreateAsset value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 6;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.CreateDomain create_domain = 7;
    public boolean hasCreateDomain() {
      return this.commandCase_ == 7;
    }
    public iroha.protocol.nano.Commands.CreateDomain getCreateDomain() {
      if (this.commandCase_ == 7) {
        return (iroha.protocol.nano.Commands.CreateDomain) this.command_;
      }
      return null;
    }
    public Command setCreateDomain(iroha.protocol.nano.Commands.CreateDomain value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 7;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.CreateRole create_role = 8;
    public boolean hasCreateRole() {
      return this.commandCase_ == 8;
    }
    public iroha.protocol.nano.Commands.CreateRole getCreateRole() {
      if (this.commandCase_ == 8) {
        return (iroha.protocol.nano.Commands.CreateRole) this.command_;
      }
      return null;
    }
    public Command setCreateRole(iroha.protocol.nano.Commands.CreateRole value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 8;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.DetachRole detach_role = 9;
    public boolean hasDetachRole() {
      return this.commandCase_ == 9;
    }
    public iroha.protocol.nano.Commands.DetachRole getDetachRole() {
      if (this.commandCase_ == 9) {
        return (iroha.protocol.nano.Commands.DetachRole) this.command_;
      }
      return null;
    }
    public Command setDetachRole(iroha.protocol.nano.Commands.DetachRole value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 9;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.GrantPermission grant_permission = 10;
    public boolean hasGrantPermission() {
      return this.commandCase_ == 10;
    }
    public iroha.protocol.nano.Commands.GrantPermission getGrantPermission() {
      if (this.commandCase_ == 10) {
        return (iroha.protocol.nano.Commands.GrantPermission) this.command_;
      }
      return null;
    }
    public Command setGrantPermission(iroha.protocol.nano.Commands.GrantPermission value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 10;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.RemoveSignatory remove_sign = 11;
    public boolean hasRemoveSign() {
      return this.commandCase_ == 11;
    }
    public iroha.protocol.nano.Commands.RemoveSignatory getRemoveSign() {
      if (this.commandCase_ == 11) {
        return (iroha.protocol.nano.Commands.RemoveSignatory) this.command_;
      }
      return null;
    }
    public Command setRemoveSign(iroha.protocol.nano.Commands.RemoveSignatory value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 11;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.RevokePermission revoke_permission = 12;
    public boolean hasRevokePermission() {
      return this.commandCase_ == 12;
    }
    public iroha.protocol.nano.Commands.RevokePermission getRevokePermission() {
      if (this.commandCase_ == 12) {
        return (iroha.protocol.nano.Commands.RevokePermission) this.command_;
      }
      return null;
    }
    public Command setRevokePermission(iroha.protocol.nano.Commands.RevokePermission value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 12;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.SetAccountDetail set_account_detail = 13;
    public boolean hasSetAccountDetail() {
      return this.commandCase_ == 13;
    }
    public iroha.protocol.nano.Commands.SetAccountDetail getSetAccountDetail() {
      if (this.commandCase_ == 13) {
        return (iroha.protocol.nano.Commands.SetAccountDetail) this.command_;
      }
      return null;
    }
    public Command setSetAccountDetail(iroha.protocol.nano.Commands.SetAccountDetail value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 13;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.SetAccountQuorum set_quorum = 14;
    public boolean hasSetQuorum() {
      return this.commandCase_ == 14;
    }
    public iroha.protocol.nano.Commands.SetAccountQuorum getSetQuorum() {
      if (this.commandCase_ == 14) {
        return (iroha.protocol.nano.Commands.SetAccountQuorum) this.command_;
      }
      return null;
    }
    public Command setSetQuorum(iroha.protocol.nano.Commands.SetAccountQuorum value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 14;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.SubtractAssetQuantity subtract_asset_quantity = 15;
    public boolean hasSubtractAssetQuantity() {
      return this.commandCase_ == 15;
    }
    public iroha.protocol.nano.Commands.SubtractAssetQuantity getSubtractAssetQuantity() {
      if (this.commandCase_ == 15) {
        return (iroha.protocol.nano.Commands.SubtractAssetQuantity) this.command_;
      }
      return null;
    }
    public Command setSubtractAssetQuantity(iroha.protocol.nano.Commands.SubtractAssetQuantity value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 15;
      this.command_ = value;
      return this;
    }

    // .iroha.protocol.TransferAsset transfer_asset = 16;
    public boolean hasTransferAsset() {
      return this.commandCase_ == 16;
    }
    public iroha.protocol.nano.Commands.TransferAsset getTransferAsset() {
      if (this.commandCase_ == 16) {
        return (iroha.protocol.nano.Commands.TransferAsset) this.command_;
      }
      return null;
    }
    public Command setTransferAsset(iroha.protocol.nano.Commands.TransferAsset value) {
      if (value == null) { throw new NullPointerException(); }
      this.commandCase_ = 16;
      this.command_ = value;
      return this;
    }

    public Command() {
      clear();
    }

    public Command clear() {
      clearCommand();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.commandCase_ == 1) {
        output.writeMessage(1,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 4) {
        output.writeMessage(4,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 5) {
        output.writeMessage(5,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 6) {
        output.writeMessage(6,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 7) {
        output.writeMessage(7,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 8) {
        output.writeMessage(8,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 9) {
        output.writeMessage(9,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 10) {
        output.writeMessage(10,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 11) {
        output.writeMessage(11,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 12) {
        output.writeMessage(12,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 13) {
        output.writeMessage(13,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 14) {
        output.writeMessage(14,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 15) {
        output.writeMessage(15,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 16) {
        output.writeMessage(16,
            (com.google.protobuf.nano.MessageNano) this.command_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.commandCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 4) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 5) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 6) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 7) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 8) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(8,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 9) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 10) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(10,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 11) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(11,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 12) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(12,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 13) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(13,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 14) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(14,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 15) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(15,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      if (this.commandCase_ == 16) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(16,
              (com.google.protobuf.nano.MessageNano) this.command_);
      }
      return size;
    }

    @Override
    public Command mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (!(this.commandCase_ == 1)) {
              this.command_ = new iroha.protocol.nano.Commands.AddAssetQuantity();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 1;
            break;
          }
          case 18: {
            if (!(this.commandCase_ == 2)) {
              this.command_ = new iroha.protocol.nano.Commands.AddPeer();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.commandCase_ == 3)) {
              this.command_ = new iroha.protocol.nano.Commands.AddSignatory();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 3;
            break;
          }
          case 34: {
            if (!(this.commandCase_ == 4)) {
              this.command_ = new iroha.protocol.nano.Commands.AppendRole();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 4;
            break;
          }
          case 42: {
            if (!(this.commandCase_ == 5)) {
              this.command_ = new iroha.protocol.nano.Commands.CreateAccount();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 5;
            break;
          }
          case 50: {
            if (!(this.commandCase_ == 6)) {
              this.command_ = new iroha.protocol.nano.Commands.CreateAsset();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 6;
            break;
          }
          case 58: {
            if (!(this.commandCase_ == 7)) {
              this.command_ = new iroha.protocol.nano.Commands.CreateDomain();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 7;
            break;
          }
          case 66: {
            if (!(this.commandCase_ == 8)) {
              this.command_ = new iroha.protocol.nano.Commands.CreateRole();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 8;
            break;
          }
          case 74: {
            if (!(this.commandCase_ == 9)) {
              this.command_ = new iroha.protocol.nano.Commands.DetachRole();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 9;
            break;
          }
          case 82: {
            if (!(this.commandCase_ == 10)) {
              this.command_ = new iroha.protocol.nano.Commands.GrantPermission();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 10;
            break;
          }
          case 90: {
            if (!(this.commandCase_ == 11)) {
              this.command_ = new iroha.protocol.nano.Commands.RemoveSignatory();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 11;
            break;
          }
          case 98: {
            if (!(this.commandCase_ == 12)) {
              this.command_ = new iroha.protocol.nano.Commands.RevokePermission();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 12;
            break;
          }
          case 106: {
            if (!(this.commandCase_ == 13)) {
              this.command_ = new iroha.protocol.nano.Commands.SetAccountDetail();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 13;
            break;
          }
          case 114: {
            if (!(this.commandCase_ == 14)) {
              this.command_ = new iroha.protocol.nano.Commands.SetAccountQuorum();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 14;
            break;
          }
          case 122: {
            if (!(this.commandCase_ == 15)) {
              this.command_ = new iroha.protocol.nano.Commands.SubtractAssetQuantity();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 15;
            break;
          }
          case 130: {
            if (!(this.commandCase_ == 16)) {
              this.command_ = new iroha.protocol.nano.Commands.TransferAsset();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.command_);
            this.commandCase_ = 16;
            break;
          }
        }
      }
    }

    public static Command parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Command(), data);
    }

    public static Command parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Command().mergeFrom(input);
    }
  }
}
