// Generated by the protocol buffer compiler.  DO NOT EDIT!

package iroha.protocol.nano;

@SuppressWarnings("hiding")
public interface Endpoint {

  // enum TxStatus
  public static final int STATELESS_VALIDATION_FAILED = 0;
  public static final int STATELESS_VALIDATION_SUCCESS = 1;
  public static final int STATEFUL_VALIDATION_FAILED = 2;
  public static final int STATEFUL_VALIDATION_SUCCESS = 3;
  public static final int COMMITTED = 4;
  public static final int NOT_RECEIVED = 5;

  public static final class ToriiResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ToriiResponse[] _emptyArray;
    public static ToriiResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ToriiResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.TxStatus tx_status = 1;
    public int txStatus;

    // bytes tx_hash = 2;
    public byte[] txHash;

    public ToriiResponse() {
      clear();
    }

    public ToriiResponse clear() {
      txStatus = Endpoint.STATELESS_VALIDATION_FAILED;
      txHash = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.txStatus != Endpoint.STATELESS_VALIDATION_FAILED) {
        output.writeInt32(1, this.txStatus);
      }
      if (!java.util.Arrays.equals(this.txHash, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.txHash);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.txStatus != Endpoint.STATELESS_VALIDATION_FAILED) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.txStatus);
      }
      if (!java.util.Arrays.equals(this.txHash, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.txHash);
      }
      return size;
    }

    @Override
    public ToriiResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case Endpoint.STATELESS_VALIDATION_FAILED:
              case Endpoint.STATELESS_VALIDATION_SUCCESS:
              case Endpoint.STATEFUL_VALIDATION_FAILED:
              case Endpoint.STATEFUL_VALIDATION_SUCCESS:
              case Endpoint.COMMITTED:
              case Endpoint.NOT_RECEIVED:
                this.txStatus = value;
                break;
            }
            break;
          }
          case 18: {
            this.txHash = input.readBytes();
            break;
          }
        }
      }
    }

    public static ToriiResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ToriiResponse(), data);
    }

    public static ToriiResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ToriiResponse().mergeFrom(input);
    }
  }

  public static final class TxStatusRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TxStatusRequest[] _emptyArray;
    public static TxStatusRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxStatusRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // bytes tx_hash = 1;
    public byte[] txHash;

    public TxStatusRequest() {
      clear();
    }

    public TxStatusRequest clear() {
      txHash = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.txHash, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.txHash);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.txHash, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.txHash);
      }
      return size;
    }

    @Override
    public TxStatusRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.txHash = input.readBytes();
            break;
          }
        }
      }
    }

    public static TxStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxStatusRequest(), data);
    }

    public static TxStatusRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxStatusRequest().mergeFrom(input);
    }
  }
}
