// Generated by the protocol buffer compiler.  DO NOT EDIT!

package iroha.protocol.nano;

@SuppressWarnings("hiding")
public interface Primitive {

  // enum RolePermission
  public static final int can_append_role = 0;
  public static final int can_create_role = 1;
  public static final int can_detach_role = 2;
  public static final int can_add_asset_qty = 3;
  public static final int can_subtract_asset_qty = 4;
  public static final int can_add_peer = 5;
  public static final int can_add_signatory = 6;
  public static final int can_remove_signatory = 7;
  public static final int can_set_quorum = 8;
  public static final int can_create_account = 9;
  public static final int can_set_detail = 10;
  public static final int can_create_asset = 11;
  public static final int can_transfer = 12;
  public static final int can_receive = 13;
  public static final int can_create_domain = 14;
  public static final int can_read_assets = 15;
  public static final int can_get_roles = 16;
  public static final int can_get_my_account = 17;
  public static final int can_get_all_accounts = 18;
  public static final int can_get_domain_accounts = 19;
  public static final int can_get_my_signatories = 20;
  public static final int can_get_all_signatories = 21;
  public static final int can_get_domain_signatories = 22;
  public static final int can_get_my_acc_ast = 23;
  public static final int can_get_all_acc_ast = 24;
  public static final int can_get_domain_acc_ast = 25;
  public static final int can_get_my_acc_detail = 26;
  public static final int can_get_all_acc_detail = 27;
  public static final int can_get_domain_acc_detail = 28;
  public static final int can_get_my_acc_txs = 29;
  public static final int can_get_all_acc_txs = 30;
  public static final int can_get_domain_acc_txs = 31;
  public static final int can_get_my_acc_ast_txs = 32;
  public static final int can_get_all_acc_ast_txs = 33;
  public static final int can_get_domain_acc_ast_txs = 34;
  public static final int can_get_my_txs = 35;
  public static final int can_get_all_txs = 36;
  public static final int can_grant_can_set_quorum = 37;
  public static final int can_grant_can_add_signatory = 38;
  public static final int can_grant_can_remove_signatory = 39;
  public static final int can_grant_can_transfer = 40;
  public static final int can_grant_can_set_detail = 41;

  // enum GrantablePermission
  public static final int can_add_my_signatory = 0;
  public static final int can_remove_my_signatory = 1;
  public static final int can_set_my_quorum = 2;
  public static final int can_set_my_account_detail = 3;
  public static final int can_transfer_my_assets = 4;

  public static final class Signature extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Signature[] _emptyArray;
    public static Signature[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Signature[0];
          }
        }
      }
      return _emptyArray;
    }

    // bytes pubkey = 1;
    public byte[] pubkey;

    // bytes signature = 2;
    public byte[] signature;

    public Signature() {
      clear();
    }

    public Signature clear() {
      pubkey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      signature = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.pubkey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.pubkey);
      }
      if (!java.util.Arrays.equals(this.signature, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.signature);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.pubkey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.pubkey);
      }
      if (!java.util.Arrays.equals(this.signature, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.signature);
      }
      return size;
    }

    @Override
    public Signature mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.pubkey = input.readBytes();
            break;
          }
          case 18: {
            this.signature = input.readBytes();
            break;
          }
        }
      }
    }

    public static Signature parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Signature(), data);
    }

    public static Signature parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Signature().mergeFrom(input);
    }
  }

  public static final class uint256 extends
      com.google.protobuf.nano.MessageNano {

    private static volatile uint256[] _emptyArray;
    public static uint256[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new uint256[0];
          }
        }
      }
      return _emptyArray;
    }

    // uint64 first = 1;
    public long first;

    // uint64 second = 2;
    public long second;

    // uint64 third = 3;
    public long third;

    // uint64 fourth = 4;
    public long fourth;

    public uint256() {
      clear();
    }

    public uint256 clear() {
      first = 0L;
      second = 0L;
      third = 0L;
      fourth = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.first != 0L) {
        output.writeUInt64(1, this.first);
      }
      if (this.second != 0L) {
        output.writeUInt64(2, this.second);
      }
      if (this.third != 0L) {
        output.writeUInt64(3, this.third);
      }
      if (this.fourth != 0L) {
        output.writeUInt64(4, this.fourth);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.first != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.first);
      }
      if (this.second != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.second);
      }
      if (this.third != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(3, this.third);
      }
      if (this.fourth != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(4, this.fourth);
      }
      return size;
    }

    @Override
    public uint256 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.first = input.readUInt64();
            break;
          }
          case 16: {
            this.second = input.readUInt64();
            break;
          }
          case 24: {
            this.third = input.readUInt64();
            break;
          }
          case 32: {
            this.fourth = input.readUInt64();
            break;
          }
        }
      }
    }

    public static uint256 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new uint256(), data);
    }

    public static uint256 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new uint256().mergeFrom(input);
    }
  }

  public static final class Amount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Amount[] _emptyArray;
    public static Amount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Amount[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.uint256 value = 1;
    public iroha.protocol.nano.Primitive.uint256 value;

    // uint32 precision = 2;
    public int precision;

    public Amount() {
      clear();
    }

    public Amount clear() {
      value = null;
      precision = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.value != null) {
        output.writeMessage(1, this.value);
      }
      if (this.precision != 0) {
        output.writeUInt32(2, this.precision);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.value != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.value);
      }
      if (this.precision != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.precision);
      }
      return size;
    }

    @Override
    public Amount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.value == null) {
              this.value = new iroha.protocol.nano.Primitive.uint256();
            }
            input.readMessage(this.value);
            break;
          }
          case 16: {
            this.precision = input.readUInt32();
            break;
          }
        }
      }
    }

    public static Amount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Amount(), data);
    }

    public static Amount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Amount().mergeFrom(input);
    }
  }

  public static final class Peer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Peer[] _emptyArray;
    public static Peer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Peer[0];
          }
        }
      }
      return _emptyArray;
    }

    // string address = 1;
    public String address;

    // bytes peer_key = 2;
    public byte[] peerKey;

    public Peer() {
      clear();
    }

    public Peer clear() {
      address = "";
      peerKey = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.address.equals("")) {
        output.writeString(1, this.address);
      }
      if (!java.util.Arrays.equals(this.peerKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.peerKey);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.address.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.address);
      }
      if (!java.util.Arrays.equals(this.peerKey, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.peerKey);
      }
      return size;
    }

    @Override
    public Peer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.address = input.readString();
            break;
          }
          case 18: {
            this.peerKey = input.readBytes();
            break;
          }
        }
      }
    }

    public static Peer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Peer(), data);
    }

    public static Peer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Peer().mergeFrom(input);
    }
  }
}
