// Generated by the protocol buffer compiler.  DO NOT EDIT!

package iroha.protocol.nano;

@SuppressWarnings("hiding")
public interface Queries {

  public static final class GetAccount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetAccount[] _emptyArray;
    public static GetAccount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetAccount[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    public GetAccount() {
      clear();
    }

    public GetAccount clear() {
      accountId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      return size;
    }

    @Override
    public GetAccount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
        }
      }
    }

    public static GetAccount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetAccount(), data);
    }

    public static GetAccount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetAccount().mergeFrom(input);
    }
  }

  public static final class GetSignatories extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetSignatories[] _emptyArray;
    public static GetSignatories[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetSignatories[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    public GetSignatories() {
      clear();
    }

    public GetSignatories clear() {
      accountId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      return size;
    }

    @Override
    public GetSignatories mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
        }
      }
    }

    public static GetSignatories parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetSignatories(), data);
    }

    public static GetSignatories parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetSignatories().mergeFrom(input);
    }
  }

  public static final class GetAccountTransactions extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetAccountTransactions[] _emptyArray;
    public static GetAccountTransactions[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetAccountTransactions[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    public GetAccountTransactions() {
      clear();
    }

    public GetAccountTransactions clear() {
      accountId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      return size;
    }

    @Override
    public GetAccountTransactions mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
        }
      }
    }

    public static GetAccountTransactions parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetAccountTransactions(), data);
    }

    public static GetAccountTransactions parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetAccountTransactions().mergeFrom(input);
    }
  }

  public static final class GetAccountAssetTransactions extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetAccountAssetTransactions[] _emptyArray;
    public static GetAccountAssetTransactions[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetAccountAssetTransactions[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string asset_id = 2;
    public String assetId;

    public GetAccountAssetTransactions() {
      clear();
    }

    public GetAccountAssetTransactions clear() {
      accountId = "";
      assetId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        output.writeString(2, this.assetId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.assetId);
      }
      return size;
    }

    @Override
    public GetAccountAssetTransactions mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.assetId = input.readString();
            break;
          }
        }
      }
    }

    public static GetAccountAssetTransactions parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetAccountAssetTransactions(), data);
    }

    public static GetAccountAssetTransactions parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetAccountAssetTransactions().mergeFrom(input);
    }
  }

  public static final class GetTransactions extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetTransactions[] _emptyArray;
    public static GetTransactions[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetTransactions[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated bytes tx_hashes = 1;
    public byte[][] txHashes;

    public GetTransactions() {
      clear();
    }

    public GetTransactions clear() {
      txHashes = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.txHashes != null && this.txHashes.length > 0) {
        for (int i = 0; i < this.txHashes.length; i++) {
          byte[] element = this.txHashes[i];
          if (element != null) {
            output.writeBytes(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.txHashes != null && this.txHashes.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.txHashes.length; i++) {
          byte[] element = this.txHashes[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public GetTransactions mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.txHashes == null ? 0 : this.txHashes.length;
            byte[][] newArray = new byte[i + arrayLength][];
            if (i != 0) {
              System.arraycopy(this.txHashes, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readBytes();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readBytes();
            this.txHashes = newArray;
            break;
          }
        }
      }
    }

    public static GetTransactions parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetTransactions(), data);
    }

    public static GetTransactions parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetTransactions().mergeFrom(input);
    }
  }

  public static final class GetAccountAssets extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetAccountAssets[] _emptyArray;
    public static GetAccountAssets[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetAccountAssets[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string asset_id = 2;
    public String assetId;

    public GetAccountAssets() {
      clear();
    }

    public GetAccountAssets clear() {
      accountId = "";
      assetId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        output.writeString(2, this.assetId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.assetId);
      }
      return size;
    }

    @Override
    public GetAccountAssets mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.assetId = input.readString();
            break;
          }
        }
      }
    }

    public static GetAccountAssets parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetAccountAssets(), data);
    }

    public static GetAccountAssets parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetAccountAssets().mergeFrom(input);
    }
  }

  public static final class GetAccountDetail extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetAccountDetail[] _emptyArray;
    public static GetAccountDetail[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetAccountDetail[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    public GetAccountDetail() {
      clear();
    }

    public GetAccountDetail clear() {
      accountId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      return size;
    }

    @Override
    public GetAccountDetail mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
        }
      }
    }

    public static GetAccountDetail parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetAccountDetail(), data);
    }

    public static GetAccountDetail parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetAccountDetail().mergeFrom(input);
    }
  }

  public static final class GetAssetInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetAssetInfo[] _emptyArray;
    public static GetAssetInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetAssetInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // string asset_id = 1;
    public String assetId;

    public GetAssetInfo() {
      clear();
    }

    public GetAssetInfo clear() {
      assetId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.assetId.equals("")) {
        output.writeString(1, this.assetId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.assetId);
      }
      return size;
    }

    @Override
    public GetAssetInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.assetId = input.readString();
            break;
          }
        }
      }
    }

    public static GetAssetInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetAssetInfo(), data);
    }

    public static GetAssetInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetAssetInfo().mergeFrom(input);
    }
  }

  public static final class GetRoles extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetRoles[] _emptyArray;
    public static GetRoles[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetRoles[0];
          }
        }
      }
      return _emptyArray;
    }

    public GetRoles() {
      clear();
    }

    public GetRoles clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public GetRoles mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static GetRoles parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetRoles(), data);
    }

    public static GetRoles parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetRoles().mergeFrom(input);
    }
  }

  public static final class GetRolePermissions extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetRolePermissions[] _emptyArray;
    public static GetRolePermissions[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetRolePermissions[0];
          }
        }
      }
      return _emptyArray;
    }

    // string role_id = 1;
    public String roleId;

    public GetRolePermissions() {
      clear();
    }

    public GetRolePermissions clear() {
      roleId = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.roleId.equals("")) {
        output.writeString(1, this.roleId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.roleId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.roleId);
      }
      return size;
    }

    @Override
    public GetRolePermissions mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.roleId = input.readString();
            break;
          }
        }
      }
    }

    public static GetRolePermissions parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetRolePermissions(), data);
    }

    public static GetRolePermissions parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetRolePermissions().mergeFrom(input);
    }
  }

  public static final class Query extends
      com.google.protobuf.nano.MessageNano {

    public static final class Payload extends
        com.google.protobuf.nano.MessageNano {
      public static final int GET_ACCOUNT_FIELD_NUMBER = 3;
      public static final int GET_ACCOUNT_SIGNATORIES_FIELD_NUMBER = 4;
      public static final int GET_ACCOUNT_TRANSACTIONS_FIELD_NUMBER = 5;
      public static final int GET_ACCOUNT_ASSET_TRANSACTIONS_FIELD_NUMBER = 6;
      public static final int GET_TRANSACTIONS_FIELD_NUMBER = 7;
      public static final int GET_ACCOUNT_ASSETS_FIELD_NUMBER = 8;
      public static final int GET_ACCOUNT_DETAIL_FIELD_NUMBER = 9;
      public static final int GET_ROLES_FIELD_NUMBER = 10;
      public static final int GET_ROLE_PERMISSIONS_FIELD_NUMBER = 11;
      public static final int GET_ASSET_INFO_FIELD_NUMBER = 12;
      private int queryCase_ = 0;
      private Object query_;
      public int getQueryCase() {
        return this.queryCase_;
      }
      public Payload clearQuery() {
        this.queryCase_ = 0;
        this.query_ = null;
        return this;
      }

      private static volatile Payload[] _emptyArray;
      public static Payload[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Payload[0];
            }
          }
        }
        return _emptyArray;
      }

      // uint64 created_time = 1;
      public long createdTime;

      // string creator_account_id = 2;
      public String creatorAccountId;

      // .iroha.protocol.GetAccount get_account = 3;
      public boolean hasGetAccount() {
        return this.queryCase_ == 3;
      }
      public iroha.protocol.nano.Queries.GetAccount getGetAccount() {
        if (this.queryCase_ == 3) {
          return (iroha.protocol.nano.Queries.GetAccount) this.query_;
        }
        return null;
      }
      public Payload setGetAccount(iroha.protocol.nano.Queries.GetAccount value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 3;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetSignatories get_account_signatories = 4;
      public boolean hasGetAccountSignatories() {
        return this.queryCase_ == 4;
      }
      public iroha.protocol.nano.Queries.GetSignatories getGetAccountSignatories() {
        if (this.queryCase_ == 4) {
          return (iroha.protocol.nano.Queries.GetSignatories) this.query_;
        }
        return null;
      }
      public Payload setGetAccountSignatories(iroha.protocol.nano.Queries.GetSignatories value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 4;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetAccountTransactions get_account_transactions = 5;
      public boolean hasGetAccountTransactions() {
        return this.queryCase_ == 5;
      }
      public iroha.protocol.nano.Queries.GetAccountTransactions getGetAccountTransactions() {
        if (this.queryCase_ == 5) {
          return (iroha.protocol.nano.Queries.GetAccountTransactions) this.query_;
        }
        return null;
      }
      public Payload setGetAccountTransactions(iroha.protocol.nano.Queries.GetAccountTransactions value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 5;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetAccountAssetTransactions get_account_asset_transactions = 6;
      public boolean hasGetAccountAssetTransactions() {
        return this.queryCase_ == 6;
      }
      public iroha.protocol.nano.Queries.GetAccountAssetTransactions getGetAccountAssetTransactions() {
        if (this.queryCase_ == 6) {
          return (iroha.protocol.nano.Queries.GetAccountAssetTransactions) this.query_;
        }
        return null;
      }
      public Payload setGetAccountAssetTransactions(iroha.protocol.nano.Queries.GetAccountAssetTransactions value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 6;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetTransactions get_transactions = 7;
      public boolean hasGetTransactions() {
        return this.queryCase_ == 7;
      }
      public iroha.protocol.nano.Queries.GetTransactions getGetTransactions() {
        if (this.queryCase_ == 7) {
          return (iroha.protocol.nano.Queries.GetTransactions) this.query_;
        }
        return null;
      }
      public Payload setGetTransactions(iroha.protocol.nano.Queries.GetTransactions value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 7;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetAccountAssets get_account_assets = 8;
      public boolean hasGetAccountAssets() {
        return this.queryCase_ == 8;
      }
      public iroha.protocol.nano.Queries.GetAccountAssets getGetAccountAssets() {
        if (this.queryCase_ == 8) {
          return (iroha.protocol.nano.Queries.GetAccountAssets) this.query_;
        }
        return null;
      }
      public Payload setGetAccountAssets(iroha.protocol.nano.Queries.GetAccountAssets value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 8;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetAccountDetail get_account_detail = 9;
      public boolean hasGetAccountDetail() {
        return this.queryCase_ == 9;
      }
      public iroha.protocol.nano.Queries.GetAccountDetail getGetAccountDetail() {
        if (this.queryCase_ == 9) {
          return (iroha.protocol.nano.Queries.GetAccountDetail) this.query_;
        }
        return null;
      }
      public Payload setGetAccountDetail(iroha.protocol.nano.Queries.GetAccountDetail value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 9;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetRoles get_roles = 10;
      public boolean hasGetRoles() {
        return this.queryCase_ == 10;
      }
      public iroha.protocol.nano.Queries.GetRoles getGetRoles() {
        if (this.queryCase_ == 10) {
          return (iroha.protocol.nano.Queries.GetRoles) this.query_;
        }
        return null;
      }
      public Payload setGetRoles(iroha.protocol.nano.Queries.GetRoles value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 10;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetRolePermissions get_role_permissions = 11;
      public boolean hasGetRolePermissions() {
        return this.queryCase_ == 11;
      }
      public iroha.protocol.nano.Queries.GetRolePermissions getGetRolePermissions() {
        if (this.queryCase_ == 11) {
          return (iroha.protocol.nano.Queries.GetRolePermissions) this.query_;
        }
        return null;
      }
      public Payload setGetRolePermissions(iroha.protocol.nano.Queries.GetRolePermissions value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 11;
        this.query_ = value;
        return this;
      }

      // .iroha.protocol.GetAssetInfo get_asset_info = 12;
      public boolean hasGetAssetInfo() {
        return this.queryCase_ == 12;
      }
      public iroha.protocol.nano.Queries.GetAssetInfo getGetAssetInfo() {
        if (this.queryCase_ == 12) {
          return (iroha.protocol.nano.Queries.GetAssetInfo) this.query_;
        }
        return null;
      }
      public Payload setGetAssetInfo(iroha.protocol.nano.Queries.GetAssetInfo value) {
        if (value == null) { throw new NullPointerException(); }
        this.queryCase_ = 12;
        this.query_ = value;
        return this;
      }

      // uint64 query_counter = 13;
      public long queryCounter;

      public Payload() {
        clear();
      }

      public Payload clear() {
        createdTime = 0L;
        creatorAccountId = "";
        queryCounter = 0L;
        clearQuery();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.createdTime != 0L) {
          output.writeUInt64(1, this.createdTime);
        }
        if (!this.creatorAccountId.equals("")) {
          output.writeString(2, this.creatorAccountId);
        }
        if (this.queryCase_ == 3) {
          output.writeMessage(3,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 4) {
          output.writeMessage(4,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 5) {
          output.writeMessage(5,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 6) {
          output.writeMessage(6,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 7) {
          output.writeMessage(7,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 8) {
          output.writeMessage(8,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 9) {
          output.writeMessage(9,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 10) {
          output.writeMessage(10,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 11) {
          output.writeMessage(11,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 12) {
          output.writeMessage(12,
              (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCounter != 0L) {
          output.writeUInt64(13, this.queryCounter);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.createdTime != 0L) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt64Size(1, this.createdTime);
        }
        if (!this.creatorAccountId.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.creatorAccountId);
        }
        if (this.queryCase_ == 3) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(3,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 4) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(4,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 5) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(5,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 6) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(6,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 7) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(7,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 8) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(8,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 9) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(9,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 10) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(10,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 11) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(11,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCase_ == 12) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(12,
                (com.google.protobuf.nano.MessageNano) this.query_);
        }
        if (this.queryCounter != 0L) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt64Size(13, this.queryCounter);
        }
        return size;
      }

      @Override
      public Payload mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.createdTime = input.readUInt64();
              break;
            }
            case 18: {
              this.creatorAccountId = input.readString();
              break;
            }
            case 26: {
              if (!(this.queryCase_ == 3)) {
                this.query_ = new iroha.protocol.nano.Queries.GetAccount();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 3;
              break;
            }
            case 34: {
              if (!(this.queryCase_ == 4)) {
                this.query_ = new iroha.protocol.nano.Queries.GetSignatories();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 4;
              break;
            }
            case 42: {
              if (!(this.queryCase_ == 5)) {
                this.query_ = new iroha.protocol.nano.Queries.GetAccountTransactions();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 5;
              break;
            }
            case 50: {
              if (!(this.queryCase_ == 6)) {
                this.query_ = new iroha.protocol.nano.Queries.GetAccountAssetTransactions();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 6;
              break;
            }
            case 58: {
              if (!(this.queryCase_ == 7)) {
                this.query_ = new iroha.protocol.nano.Queries.GetTransactions();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 7;
              break;
            }
            case 66: {
              if (!(this.queryCase_ == 8)) {
                this.query_ = new iroha.protocol.nano.Queries.GetAccountAssets();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 8;
              break;
            }
            case 74: {
              if (!(this.queryCase_ == 9)) {
                this.query_ = new iroha.protocol.nano.Queries.GetAccountDetail();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 9;
              break;
            }
            case 82: {
              if (!(this.queryCase_ == 10)) {
                this.query_ = new iroha.protocol.nano.Queries.GetRoles();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 10;
              break;
            }
            case 90: {
              if (!(this.queryCase_ == 11)) {
                this.query_ = new iroha.protocol.nano.Queries.GetRolePermissions();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 11;
              break;
            }
            case 98: {
              if (!(this.queryCase_ == 12)) {
                this.query_ = new iroha.protocol.nano.Queries.GetAssetInfo();
              }
              input.readMessage(
                  (com.google.protobuf.nano.MessageNano) this.query_);
              this.queryCase_ = 12;
              break;
            }
            case 104: {
              this.queryCounter = input.readUInt64();
              break;
            }
          }
        }
      }

      public static Payload parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Payload(), data);
      }

      public static Payload parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Payload().mergeFrom(input);
      }
    }

    private static volatile Query[] _emptyArray;
    public static Query[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Query[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.Query.Payload payload = 1;
    public iroha.protocol.nano.Queries.Query.Payload payload;

    // .iroha.protocol.Signature signature = 2;
    public iroha.protocol.nano.Primitive.Signature signature;

    public Query() {
      clear();
    }

    public Query clear() {
      payload = null;
      signature = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.payload != null) {
        output.writeMessage(1, this.payload);
      }
      if (this.signature != null) {
        output.writeMessage(2, this.signature);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.payload != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.payload);
      }
      if (this.signature != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.signature);
      }
      return size;
    }

    @Override
    public Query mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.payload == null) {
              this.payload = new iroha.protocol.nano.Queries.Query.Payload();
            }
            input.readMessage(this.payload);
            break;
          }
          case 18: {
            if (this.signature == null) {
              this.signature = new iroha.protocol.nano.Primitive.Signature();
            }
            input.readMessage(this.signature);
            break;
          }
        }
      }
    }

    public static Query parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Query(), data);
    }

    public static Query parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Query().mergeFrom(input);
    }
  }
}
