// Generated by the protocol buffer compiler.  DO NOT EDIT!

package iroha.protocol.nano;

@SuppressWarnings("hiding")
public interface Responses {

  public static final class Asset extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Asset[] _emptyArray;
    public static Asset[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Asset[0];
          }
        }
      }
      return _emptyArray;
    }

    // string asset_id = 1;
    public String assetId;

    // string domain_id = 2;
    public String domainId;

    // uint32 precision = 3;
    public int precision;

    public Asset() {
      clear();
    }

    public Asset clear() {
      assetId = "";
      domainId = "";
      precision = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.assetId.equals("")) {
        output.writeString(1, this.assetId);
      }
      if (!this.domainId.equals("")) {
        output.writeString(2, this.domainId);
      }
      if (this.precision != 0) {
        output.writeUInt32(3, this.precision);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.assetId);
      }
      if (!this.domainId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.domainId);
      }
      if (this.precision != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.precision);
      }
      return size;
    }

    @Override
    public Asset mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.assetId = input.readString();
            break;
          }
          case 18: {
            this.domainId = input.readString();
            break;
          }
          case 24: {
            this.precision = input.readUInt32();
            break;
          }
        }
      }
    }

    public static Asset parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Asset(), data);
    }

    public static Asset parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Asset().mergeFrom(input);
    }
  }

  public static final class Domain extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Domain[] _emptyArray;
    public static Domain[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Domain[0];
          }
        }
      }
      return _emptyArray;
    }

    // string domain_id = 1;
    public String domainId;

    // string default_role = 2;
    public String defaultRole;

    public Domain() {
      clear();
    }

    public Domain clear() {
      domainId = "";
      defaultRole = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.domainId.equals("")) {
        output.writeString(1, this.domainId);
      }
      if (!this.defaultRole.equals("")) {
        output.writeString(2, this.defaultRole);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.domainId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.domainId);
      }
      if (!this.defaultRole.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.defaultRole);
      }
      return size;
    }

    @Override
    public Domain mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.domainId = input.readString();
            break;
          }
          case 18: {
            this.defaultRole = input.readString();
            break;
          }
        }
      }
    }

    public static Domain parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Domain(), data);
    }

    public static Domain parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Domain().mergeFrom(input);
    }
  }

  public static final class Account extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Account[] _emptyArray;
    public static Account[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Account[0];
          }
        }
      }
      return _emptyArray;
    }

    // string account_id = 1;
    public String accountId;

    // string domain_id = 2;
    public String domainId;

    // uint32 quorum = 3;
    public int quorum;

    // string json_data = 4;
    public String jsonData;

    public Account() {
      clear();
    }

    public Account clear() {
      accountId = "";
      domainId = "";
      quorum = 0;
      jsonData = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accountId.equals("")) {
        output.writeString(1, this.accountId);
      }
      if (!this.domainId.equals("")) {
        output.writeString(2, this.domainId);
      }
      if (this.quorum != 0) {
        output.writeUInt32(3, this.quorum);
      }
      if (!this.jsonData.equals("")) {
        output.writeString(4, this.jsonData);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accountId);
      }
      if (!this.domainId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.domainId);
      }
      if (this.quorum != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.quorum);
      }
      if (!this.jsonData.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.jsonData);
      }
      return size;
    }

    @Override
    public Account mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accountId = input.readString();
            break;
          }
          case 18: {
            this.domainId = input.readString();
            break;
          }
          case 24: {
            this.quorum = input.readUInt32();
            break;
          }
          case 34: {
            this.jsonData = input.readString();
            break;
          }
        }
      }
    }

    public static Account parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Account(), data);
    }

    public static Account parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Account().mergeFrom(input);
    }
  }

  public static final class AccountAsset extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AccountAsset[] _emptyArray;
    public static AccountAsset[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AccountAsset[0];
          }
        }
      }
      return _emptyArray;
    }

    // string asset_id = 1;
    public String assetId;

    // string account_id = 2;
    public String accountId;

    // .iroha.protocol.Amount balance = 3;
    public iroha.protocol.nano.Primitive.Amount balance;

    public AccountAsset() {
      clear();
    }

    public AccountAsset clear() {
      assetId = "";
      accountId = "";
      balance = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.assetId.equals("")) {
        output.writeString(1, this.assetId);
      }
      if (!this.accountId.equals("")) {
        output.writeString(2, this.accountId);
      }
      if (this.balance != null) {
        output.writeMessage(3, this.balance);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.assetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.assetId);
      }
      if (!this.accountId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.accountId);
      }
      if (this.balance != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.balance);
      }
      return size;
    }

    @Override
    public AccountAsset mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.assetId = input.readString();
            break;
          }
          case 18: {
            this.accountId = input.readString();
            break;
          }
          case 26: {
            if (this.balance == null) {
              this.balance = new iroha.protocol.nano.Primitive.Amount();
            }
            input.readMessage(this.balance);
            break;
          }
        }
      }
    }

    public static AccountAsset parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AccountAsset(), data);
    }

    public static AccountAsset parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AccountAsset().mergeFrom(input);
    }
  }

  public static final class AccountAssetResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AccountAssetResponse[] _emptyArray;
    public static AccountAssetResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AccountAssetResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.AccountAsset account_asset = 1;
    public iroha.protocol.nano.Responses.AccountAsset accountAsset;

    public AccountAssetResponse() {
      clear();
    }

    public AccountAssetResponse clear() {
      accountAsset = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.accountAsset != null) {
        output.writeMessage(1, this.accountAsset);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.accountAsset != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.accountAsset);
      }
      return size;
    }

    @Override
    public AccountAssetResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.accountAsset == null) {
              this.accountAsset = new iroha.protocol.nano.Responses.AccountAsset();
            }
            input.readMessage(this.accountAsset);
            break;
          }
        }
      }
    }

    public static AccountAssetResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AccountAssetResponse(), data);
    }

    public static AccountAssetResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AccountAssetResponse().mergeFrom(input);
    }
  }

  public static final class AccountDetailResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AccountDetailResponse[] _emptyArray;
    public static AccountDetailResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AccountDetailResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // string detail = 1;
    public String detail;

    public AccountDetailResponse() {
      clear();
    }

    public AccountDetailResponse clear() {
      detail = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.detail.equals("")) {
        output.writeString(1, this.detail);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.detail.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.detail);
      }
      return size;
    }

    @Override
    public AccountDetailResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.detail = input.readString();
            break;
          }
        }
      }
    }

    public static AccountDetailResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AccountDetailResponse(), data);
    }

    public static AccountDetailResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AccountDetailResponse().mergeFrom(input);
    }
  }

  public static final class AccountResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AccountResponse[] _emptyArray;
    public static AccountResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AccountResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.Account account = 1;
    public iroha.protocol.nano.Responses.Account account;

    // repeated string account_roles = 2;
    public String[] accountRoles;

    public AccountResponse() {
      clear();
    }

    public AccountResponse clear() {
      account = null;
      accountRoles = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.account != null) {
        output.writeMessage(1, this.account);
      }
      if (this.accountRoles != null && this.accountRoles.length > 0) {
        for (int i = 0; i < this.accountRoles.length; i++) {
          String element = this.accountRoles[i];
          if (element != null) {
            output.writeString(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.account != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.account);
      }
      if (this.accountRoles != null && this.accountRoles.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.accountRoles.length; i++) {
          String element = this.accountRoles[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public AccountResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.account == null) {
              this.account = new iroha.protocol.nano.Responses.Account();
            }
            input.readMessage(this.account);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.accountRoles == null ? 0 : this.accountRoles.length;
            String[] newArray = new String[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.accountRoles, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.accountRoles = newArray;
            break;
          }
        }
      }
    }

    public static AccountResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AccountResponse(), data);
    }

    public static AccountResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AccountResponse().mergeFrom(input);
    }
  }

  public static final class AssetResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AssetResponse[] _emptyArray;
    public static AssetResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AssetResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.Asset asset = 1;
    public iroha.protocol.nano.Responses.Asset asset;

    public AssetResponse() {
      clear();
    }

    public AssetResponse clear() {
      asset = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.asset != null) {
        output.writeMessage(1, this.asset);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.asset != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.asset);
      }
      return size;
    }

    @Override
    public AssetResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.asset == null) {
              this.asset = new iroha.protocol.nano.Responses.Asset();
            }
            input.readMessage(this.asset);
            break;
          }
        }
      }
    }

    public static AssetResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AssetResponse(), data);
    }

    public static AssetResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AssetResponse().mergeFrom(input);
    }
  }

  public static final class RolesResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RolesResponse[] _emptyArray;
    public static RolesResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RolesResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated string roles = 1;
    public String[] roles;

    public RolesResponse() {
      clear();
    }

    public RolesResponse clear() {
      roles = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.roles != null && this.roles.length > 0) {
        for (int i = 0; i < this.roles.length; i++) {
          String element = this.roles[i];
          if (element != null) {
            output.writeString(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.roles != null && this.roles.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.roles.length; i++) {
          String element = this.roles[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public RolesResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.roles == null ? 0 : this.roles.length;
            String[] newArray = new String[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.roles, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.roles = newArray;
            break;
          }
        }
      }
    }

    public static RolesResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RolesResponse(), data);
    }

    public static RolesResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RolesResponse().mergeFrom(input);
    }
  }

  public static final class RolePermissionsResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RolePermissionsResponse[] _emptyArray;
    public static RolePermissionsResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RolePermissionsResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated string permissions = 1;
    public String[] permissions;

    public RolePermissionsResponse() {
      clear();
    }

    public RolePermissionsResponse clear() {
      permissions = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.permissions != null && this.permissions.length > 0) {
        for (int i = 0; i < this.permissions.length; i++) {
          String element = this.permissions[i];
          if (element != null) {
            output.writeString(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.permissions != null && this.permissions.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.permissions.length; i++) {
          String element = this.permissions[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public RolePermissionsResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.permissions == null ? 0 : this.permissions.length;
            String[] newArray = new String[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.permissions, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.permissions = newArray;
            break;
          }
        }
      }
    }

    public static RolePermissionsResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RolePermissionsResponse(), data);
    }

    public static RolePermissionsResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RolePermissionsResponse().mergeFrom(input);
    }
  }

  public static final class ErrorResponse extends
      com.google.protobuf.nano.MessageNano {

    // enum Reason
    public static final int STATELESS_INVALID = 0;
    public static final int STATEFUL_INVALID = 1;
    public static final int NO_ACCOUNT = 2;
    public static final int NO_ACCOUNT_ASSETS = 3;
    public static final int NO_ACCOUNT_DETAIL = 4;
    public static final int NO_SIGNATORIES = 5;
    public static final int NOT_SUPPORTED = 6;
    public static final int NO_ASSET = 7;
    public static final int NO_ROLES = 8;

    private static volatile ErrorResponse[] _emptyArray;
    public static ErrorResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ErrorResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.ErrorResponse.Reason reason = 1;
    public int reason;

    public ErrorResponse() {
      clear();
    }

    public ErrorResponse clear() {
      reason = iroha.protocol.nano.Responses.ErrorResponse.STATELESS_INVALID;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.reason != iroha.protocol.nano.Responses.ErrorResponse.STATELESS_INVALID) {
        output.writeInt32(1, this.reason);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.reason != iroha.protocol.nano.Responses.ErrorResponse.STATELESS_INVALID) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.reason);
      }
      return size;
    }

    @Override
    public ErrorResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case iroha.protocol.nano.Responses.ErrorResponse.STATELESS_INVALID:
              case iroha.protocol.nano.Responses.ErrorResponse.STATEFUL_INVALID:
              case iroha.protocol.nano.Responses.ErrorResponse.NO_ACCOUNT:
              case iroha.protocol.nano.Responses.ErrorResponse.NO_ACCOUNT_ASSETS:
              case iroha.protocol.nano.Responses.ErrorResponse.NO_ACCOUNT_DETAIL:
              case iroha.protocol.nano.Responses.ErrorResponse.NO_SIGNATORIES:
              case iroha.protocol.nano.Responses.ErrorResponse.NOT_SUPPORTED:
              case iroha.protocol.nano.Responses.ErrorResponse.NO_ASSET:
              case iroha.protocol.nano.Responses.ErrorResponse.NO_ROLES:
                this.reason = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static ErrorResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ErrorResponse(), data);
    }

    public static ErrorResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ErrorResponse().mergeFrom(input);
    }
  }

  public static final class SignatoriesResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SignatoriesResponse[] _emptyArray;
    public static SignatoriesResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SignatoriesResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated bytes keys = 1;
    public byte[][] keys;

    public SignatoriesResponse() {
      clear();
    }

    public SignatoriesResponse clear() {
      keys = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.keys != null && this.keys.length > 0) {
        for (int i = 0; i < this.keys.length; i++) {
          byte[] element = this.keys[i];
          if (element != null) {
            output.writeBytes(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.keys != null && this.keys.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.keys.length; i++) {
          byte[] element = this.keys[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public SignatoriesResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.keys == null ? 0 : this.keys.length;
            byte[][] newArray = new byte[i + arrayLength][];
            if (i != 0) {
              System.arraycopy(this.keys, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readBytes();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readBytes();
            this.keys = newArray;
            break;
          }
        }
      }
    }

    public static SignatoriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SignatoriesResponse(), data);
    }

    public static SignatoriesResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SignatoriesResponse().mergeFrom(input);
    }
  }

  public static final class TransactionsResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TransactionsResponse[] _emptyArray;
    public static TransactionsResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TransactionsResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .iroha.protocol.Transaction transactions = 1;
    public iroha.protocol.nano.Block.Transaction[] transactions;

    public TransactionsResponse() {
      clear();
    }

    public TransactionsResponse clear() {
      transactions = iroha.protocol.nano.Block.Transaction.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.transactions != null && this.transactions.length > 0) {
        for (int i = 0; i < this.transactions.length; i++) {
          iroha.protocol.nano.Block.Transaction element = this.transactions[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.transactions != null && this.transactions.length > 0) {
        for (int i = 0; i < this.transactions.length; i++) {
          iroha.protocol.nano.Block.Transaction element = this.transactions[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public TransactionsResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.transactions == null ? 0 : this.transactions.length;
            iroha.protocol.nano.Block.Transaction[] newArray =
                new iroha.protocol.nano.Block.Transaction[i + arrayLength];
            if (i != 0) {
              System.arraycopy(this.transactions, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new iroha.protocol.nano.Block.Transaction();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new iroha.protocol.nano.Block.Transaction();
            input.readMessage(newArray[i]);
            this.transactions = newArray;
            break;
          }
        }
      }
    }

    public static TransactionsResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TransactionsResponse(), data);
    }

    public static TransactionsResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TransactionsResponse().mergeFrom(input);
    }
  }

  public static final class QueryResponse extends
      com.google.protobuf.nano.MessageNano {
    public static final int ACCOUNT_ASSETS_RESPONSE_FIELD_NUMBER = 1;
    public static final int ACCOUNT_DETAIL_RESPONSE_FIELD_NUMBER = 2;
    public static final int ACCOUNT_RESPONSE_FIELD_NUMBER = 3;
    public static final int ERROR_RESPONSE_FIELD_NUMBER = 4;
    public static final int SIGNATORIES_RESPONSE_FIELD_NUMBER = 5;
    public static final int TRANSACTIONS_RESPONSE_FIELD_NUMBER = 6;
    public static final int ASSET_RESPONSE_FIELD_NUMBER = 7;
    public static final int ROLES_RESPONSE_FIELD_NUMBER = 8;
    public static final int ROLE_PERMISSIONS_RESPONSE_FIELD_NUMBER = 9;
    private int responseCase_ = 0;
    private Object response_;
    public int getResponseCase() {
      return this.responseCase_;
    }
    public QueryResponse clearResponse() {
      this.responseCase_ = 0;
      this.response_ = null;
      return this;
    }

    private static volatile QueryResponse[] _emptyArray;
    public static QueryResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new QueryResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // .iroha.protocol.AccountAssetResponse account_assets_response = 1;
    public boolean hasAccountAssetsResponse() {
      return this.responseCase_ == 1;
    }
    public iroha.protocol.nano.Responses.AccountAssetResponse getAccountAssetsResponse() {
      if (this.responseCase_ == 1) {
        return (iroha.protocol.nano.Responses.AccountAssetResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setAccountAssetsResponse(iroha.protocol.nano.Responses.AccountAssetResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 1;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.AccountDetailResponse account_detail_response = 2;
    public boolean hasAccountDetailResponse() {
      return this.responseCase_ == 2;
    }
    public iroha.protocol.nano.Responses.AccountDetailResponse getAccountDetailResponse() {
      if (this.responseCase_ == 2) {
        return (iroha.protocol.nano.Responses.AccountDetailResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setAccountDetailResponse(iroha.protocol.nano.Responses.AccountDetailResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 2;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.AccountResponse account_response = 3;
    public boolean hasAccountResponse() {
      return this.responseCase_ == 3;
    }
    public iroha.protocol.nano.Responses.AccountResponse getAccountResponse() {
      if (this.responseCase_ == 3) {
        return (iroha.protocol.nano.Responses.AccountResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setAccountResponse(iroha.protocol.nano.Responses.AccountResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 3;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.ErrorResponse error_response = 4;
    public boolean hasErrorResponse() {
      return this.responseCase_ == 4;
    }
    public iroha.protocol.nano.Responses.ErrorResponse getErrorResponse() {
      if (this.responseCase_ == 4) {
        return (iroha.protocol.nano.Responses.ErrorResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setErrorResponse(iroha.protocol.nano.Responses.ErrorResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 4;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.SignatoriesResponse signatories_response = 5;
    public boolean hasSignatoriesResponse() {
      return this.responseCase_ == 5;
    }
    public iroha.protocol.nano.Responses.SignatoriesResponse getSignatoriesResponse() {
      if (this.responseCase_ == 5) {
        return (iroha.protocol.nano.Responses.SignatoriesResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setSignatoriesResponse(iroha.protocol.nano.Responses.SignatoriesResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 5;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.TransactionsResponse transactions_response = 6;
    public boolean hasTransactionsResponse() {
      return this.responseCase_ == 6;
    }
    public iroha.protocol.nano.Responses.TransactionsResponse getTransactionsResponse() {
      if (this.responseCase_ == 6) {
        return (iroha.protocol.nano.Responses.TransactionsResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setTransactionsResponse(iroha.protocol.nano.Responses.TransactionsResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 6;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.AssetResponse asset_response = 7;
    public boolean hasAssetResponse() {
      return this.responseCase_ == 7;
    }
    public iroha.protocol.nano.Responses.AssetResponse getAssetResponse() {
      if (this.responseCase_ == 7) {
        return (iroha.protocol.nano.Responses.AssetResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setAssetResponse(iroha.protocol.nano.Responses.AssetResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 7;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.RolesResponse roles_response = 8;
    public boolean hasRolesResponse() {
      return this.responseCase_ == 8;
    }
    public iroha.protocol.nano.Responses.RolesResponse getRolesResponse() {
      if (this.responseCase_ == 8) {
        return (iroha.protocol.nano.Responses.RolesResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setRolesResponse(iroha.protocol.nano.Responses.RolesResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 8;
      this.response_ = value;
      return this;
    }

    // .iroha.protocol.RolePermissionsResponse role_permissions_response = 9;
    public boolean hasRolePermissionsResponse() {
      return this.responseCase_ == 9;
    }
    public iroha.protocol.nano.Responses.RolePermissionsResponse getRolePermissionsResponse() {
      if (this.responseCase_ == 9) {
        return (iroha.protocol.nano.Responses.RolePermissionsResponse) this.response_;
      }
      return null;
    }
    public QueryResponse setRolePermissionsResponse(iroha.protocol.nano.Responses.RolePermissionsResponse value) {
      if (value == null) { throw new NullPointerException(); }
      this.responseCase_ = 9;
      this.response_ = value;
      return this;
    }

    // bytes query_hash = 10;
    public byte[] queryHash;

    public QueryResponse() {
      clear();
    }

    public QueryResponse clear() {
      queryHash = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      clearResponse();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.responseCase_ == 1) {
        output.writeMessage(1,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 2) {
        output.writeMessage(2,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 3) {
        output.writeMessage(3,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 4) {
        output.writeMessage(4,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 5) {
        output.writeMessage(5,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 6) {
        output.writeMessage(6,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 7) {
        output.writeMessage(7,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 8) {
        output.writeMessage(8,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 9) {
        output.writeMessage(9,
            (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (!java.util.Arrays.equals(this.queryHash, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(10, this.queryHash);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.responseCase_ == 1) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 2) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 3) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 4) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 5) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 6) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 7) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 8) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(8,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (this.responseCase_ == 9) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9,
              (com.google.protobuf.nano.MessageNano) this.response_);
      }
      if (!java.util.Arrays.equals(this.queryHash, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(10, this.queryHash);
      }
      return size;
    }

    @Override
    public QueryResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (!(this.responseCase_ == 1)) {
              this.response_ = new iroha.protocol.nano.Responses.AccountAssetResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 1;
            break;
          }
          case 18: {
            if (!(this.responseCase_ == 2)) {
              this.response_ = new iroha.protocol.nano.Responses.AccountDetailResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 2;
            break;
          }
          case 26: {
            if (!(this.responseCase_ == 3)) {
              this.response_ = new iroha.protocol.nano.Responses.AccountResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 3;
            break;
          }
          case 34: {
            if (!(this.responseCase_ == 4)) {
              this.response_ = new iroha.protocol.nano.Responses.ErrorResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 4;
            break;
          }
          case 42: {
            if (!(this.responseCase_ == 5)) {
              this.response_ = new iroha.protocol.nano.Responses.SignatoriesResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 5;
            break;
          }
          case 50: {
            if (!(this.responseCase_ == 6)) {
              this.response_ = new iroha.protocol.nano.Responses.TransactionsResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 6;
            break;
          }
          case 58: {
            if (!(this.responseCase_ == 7)) {
              this.response_ = new iroha.protocol.nano.Responses.AssetResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 7;
            break;
          }
          case 66: {
            if (!(this.responseCase_ == 8)) {
              this.response_ = new iroha.protocol.nano.Responses.RolesResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 8;
            break;
          }
          case 74: {
            if (!(this.responseCase_ == 9)) {
              this.response_ = new iroha.protocol.nano.Responses.RolePermissionsResponse();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.response_);
            this.responseCase_ = 9;
            break;
          }
          case 82: {
            this.queryHash = input.readBytes();
            break;
          }
        }
      }
    }

    public static QueryResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new QueryResponse(), data);
    }

    public static QueryResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new QueryResponse().mergeFrom(input);
    }
  }
}
